/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 41efdadd15b4466caba8e3fc803b5bbe)
interface __BaseEnv_Env {
	IMAGES: ImagesBinding;
	PG_DATABASE_URL: string;
	PG_DATABASE_URL1: string;
	VITE_BETTER_AUTH_URL: string;
	VITE_TURNSTILE_SITE_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	UPSTASH_REDIS_REST_URL: string;
	UPSTASH_REDIS_REST_TOKEN: string;
	QSTASH_URL: string;
	QSTASH_TOKEN: string;
	QSTASH_CURRENT_SIGNING_KEY: string;
	QSTASH_NEXT_SIGNING_KEY: string;
	VITE_ONESIGNAL_APP_ID: string;
	VITE_ONESIGNAL_SAFARI_WEB_ID: string;
	ONESIGNAL_API_KEY: string;
	VITE_SITE_URL: string;
	AWS_REGION: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	AWS_S3_FILES_BUCKET_NAME: string;
	VITE_AWS_CLOUDFRONT_URL: string;
	OPENROUTER_API_KEY: string;
	OPENAI_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PG_DATABASE_URL" | "PG_DATABASE_URL1" | "VITE_BETTER_AUTH_URL" | "VITE_TURNSTILE_SITE_KEY" | "TURNSTILE_SECRET_KEY" | "UPSTASH_REDIS_REST_URL" | "UPSTASH_REDIS_REST_TOKEN" | "QSTASH_URL" | "QSTASH_TOKEN" | "QSTASH_CURRENT_SIGNING_KEY" | "QSTASH_NEXT_SIGNING_KEY" | "VITE_ONESIGNAL_APP_ID" | "VITE_ONESIGNAL_SAFARI_WEB_ID" | "ONESIGNAL_API_KEY" | "VITE_SITE_URL" | "AWS_REGION" | "AWS_ACCESS_KEY_ID" | "AWS_SECRET_ACCESS_KEY" | "AWS_S3_FILES_BUCKET_NAME" | "VITE_AWS_CLOUDFRONT_URL" | "OPENROUTER_API_KEY" | "OPENAI_API_KEY">> {}
}
