/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PadajalaRouteRouteImport } from './routes/padajala/route'
import { Route as PadavaliRouteRouteImport } from './routes/padavali/route'
import { Route as CrosswordSplatRouteImport } from './routes/crossword.$'
import { Route as ApiQstashNew_puzzle_notificationRouteImport } from './routes/api/qstash/new_puzzle_notification'
import { Route as ApiQstashSave_ai_batch_resultsRouteImport } from './routes/api/qstash/save_ai_batch_results'
import { Route as ApiQstashSchedule_listingRouteImport } from './routes/api/qstash/schedule_listing'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as PadajalaauthAuthRouteImport } from './routes/padajala/(auth)/_auth'
import { Route as PadajalapublicPublicRouteImport } from './routes/padajala/(public)/_public'
import { Route as PadavaliauthAuthRouteImport } from './routes/padavali/(auth)/_auth'
import { Route as PadavalipublicPublicRouteImport } from './routes/padavali/(public)/_public'
import { Route as ApiQstashCrosswordSchedule_listingRouteImport } from './routes/api/qstash/crossword/schedule_listing'
import { Route as PadajalapublicPublicIndexRouteImport } from './routes/padajala/(public)/_public/index'
import { Route as PadajalapublicPublicSlugRouteImport } from './routes/padajala/(public)/_public/$slug'
import { Route as PadavalipublicPublicIndexRouteImport } from './routes/padavali/(public)/_public/index'
import { Route as PadavalipublicPublicSlugRouteImport } from './routes/padavali/(public)/_public/$slug'
import { Route as PadajalaauthAuthAnalyticsIndexRouteImport } from './routes/padajala/(auth)/_auth/analytics/index'
import { Route as PadajalaauthAuthBatch_managerIndexRouteImport } from './routes/padajala/(auth)/_auth/batch_manager/index'
import { Route as PadajalaauthAuthEditIdRouteImport } from './routes/padajala/(auth)/_auth/edit/$id'
import { Route as PadajalaauthAuthListIndexRouteImport } from './routes/padajala/(auth)/_auth/list/index'
import { Route as PadajalaauthAuthSchedulesIndexRouteImport } from './routes/padajala/(auth)/_auth/schedules/index'
import { Route as PadajalapublicPublicArchivedId_uuidRouteImport } from './routes/padajala/(public)/_public/archived/$id_uuid'
import { Route as PadajalapublicPublicPuzzleSlugRouteImport } from './routes/padajala/(public)/_public/puzzle/$slug'
import { Route as PadajalapublicPublicPuzzlesIndexRouteImport } from './routes/padajala/(public)/_public/puzzles/index'
import { Route as PadajalapublicPublicViewId_slugRouteImport } from './routes/padajala/(public)/_public/view/$id_slug'
import { Route as PadavaliauthAuthAnalyticsIndexRouteImport } from './routes/padavali/(auth)/_auth/analytics/index'
import { Route as PadavaliauthAuthBatch_managerIndexRouteImport } from './routes/padavali/(auth)/_auth/batch_manager/index'
import { Route as PadavaliauthAuthEditIdRouteImport } from './routes/padavali/(auth)/_auth/edit/$id'
import { Route as PadavaliauthAuthListIndexRouteImport } from './routes/padavali/(auth)/_auth/list/index'
import { Route as PadavaliauthAuthSchedulesIndexRouteImport } from './routes/padavali/(auth)/_auth/schedules/index'
import { Route as PadavalipublicPublicArchivedId_uuidRouteImport } from './routes/padavali/(public)/_public/archived/$id_uuid'
import { Route as PadavalipublicPublicPuzzleSlugRouteImport } from './routes/padavali/(public)/_public/puzzle/$slug'
import { Route as PadavalipublicPublicPuzzlesIndexRouteImport } from './routes/padavali/(public)/_public/puzzles/index'
import { Route as PadavalipublicPublicViewId_slugRouteImport } from './routes/padavali/(public)/_public/view/$id_slug'
import { Route as PadajalaauthAuthSchedulesAddIndexRouteImport } from './routes/padajala/(auth)/_auth/schedules/add/index'
import { Route as PadajalaauthAuthSchedulesEditIdRouteImport } from './routes/padajala/(auth)/_auth/schedules/edit/$id'
import { Route as PadavaliauthAuthSchedulesAddIndexRouteImport } from './routes/padavali/(auth)/_auth/schedules/add/index'
import { Route as PadavaliauthAuthSchedulesEditIdRouteImport } from './routes/padavali/(auth)/_auth/schedules/edit/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PadajalaRouteRoute = PadajalaRouteRouteImport.update({
  id: '/padajala',
  path: '/padajala',
  getParentRoute: () => rootRouteImport,
} as any)
const PadavaliRouteRoute = PadavaliRouteRouteImport.update({
  id: '/padavali',
  path: '/padavali',
  getParentRoute: () => rootRouteImport,
} as any)
const CrosswordSplatRoute = CrosswordSplatRouteImport.update({
  id: '/crossword/$',
  path: '/crossword/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQstashNew_puzzle_notificationRoute =
  ApiQstashNew_puzzle_notificationRouteImport.update({
    id: '/api/qstash/new_puzzle_notification',
    path: '/api/qstash/new_puzzle_notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQstashSave_ai_batch_resultsRoute =
  ApiQstashSave_ai_batch_resultsRouteImport.update({
    id: '/api/qstash/save_ai_batch_results',
    path: '/api/qstash/save_ai_batch_results',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQstashSchedule_listingRoute =
  ApiQstashSchedule_listingRouteImport.update({
    id: '/api/qstash/schedule_listing',
    path: '/api/qstash/schedule_listing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PadajalaauthAuthRoute = PadajalaauthAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => PadajalaRouteRoute,
} as any)
const PadajalapublicPublicRoute = PadajalapublicPublicRouteImport.update({
  id: '/(public)/_public',
  getParentRoute: () => PadajalaRouteRoute,
} as any)
const PadavaliauthAuthRoute = PadavaliauthAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => PadavaliRouteRoute,
} as any)
const PadavalipublicPublicRoute = PadavalipublicPublicRouteImport.update({
  id: '/(public)/_public',
  getParentRoute: () => PadavaliRouteRoute,
} as any)
const ApiQstashCrosswordSchedule_listingRoute =
  ApiQstashCrosswordSchedule_listingRouteImport.update({
    id: '/api/qstash/crossword/schedule_listing',
    path: '/api/qstash/crossword/schedule_listing',
    getParentRoute: () => rootRouteImport,
  } as any)
const PadajalapublicPublicIndexRoute =
  PadajalapublicPublicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PadajalapublicPublicRoute,
  } as any)
const PadajalapublicPublicSlugRoute =
  PadajalapublicPublicSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => PadajalapublicPublicRoute,
  } as any)
const PadavalipublicPublicIndexRoute =
  PadavalipublicPublicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PadavalipublicPublicRoute,
  } as any)
const PadavalipublicPublicSlugRoute =
  PadavalipublicPublicSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => PadavalipublicPublicRoute,
  } as any)
const PadajalaauthAuthAnalyticsIndexRoute =
  PadajalaauthAuthAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => PadajalaauthAuthRoute,
  } as any)
const PadajalaauthAuthBatch_managerIndexRoute =
  PadajalaauthAuthBatch_managerIndexRouteImport.update({
    id: '/batch_manager/',
    path: '/batch_manager/',
    getParentRoute: () => PadajalaauthAuthRoute,
  } as any)
const PadajalaauthAuthEditIdRoute = PadajalaauthAuthEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => PadajalaauthAuthRoute,
} as any)
const PadajalaauthAuthListIndexRoute =
  PadajalaauthAuthListIndexRouteImport.update({
    id: '/list/',
    path: '/list/',
    getParentRoute: () => PadajalaauthAuthRoute,
  } as any)
const PadajalaauthAuthSchedulesIndexRoute =
  PadajalaauthAuthSchedulesIndexRouteImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => PadajalaauthAuthRoute,
  } as any)
const PadajalapublicPublicArchivedId_uuidRoute =
  PadajalapublicPublicArchivedId_uuidRouteImport.update({
    id: '/archived/$id_uuid',
    path: '/archived/$id_uuid',
    getParentRoute: () => PadajalapublicPublicRoute,
  } as any)
const PadajalapublicPublicPuzzleSlugRoute =
  PadajalapublicPublicPuzzleSlugRouteImport.update({
    id: '/puzzle/$slug',
    path: '/puzzle/$slug',
    getParentRoute: () => PadajalapublicPublicRoute,
  } as any)
const PadajalapublicPublicPuzzlesIndexRoute =
  PadajalapublicPublicPuzzlesIndexRouteImport.update({
    id: '/puzzles/',
    path: '/puzzles/',
    getParentRoute: () => PadajalapublicPublicRoute,
  } as any)
const PadajalapublicPublicViewId_slugRoute =
  PadajalapublicPublicViewId_slugRouteImport.update({
    id: '/view/$id_slug',
    path: '/view/$id_slug',
    getParentRoute: () => PadajalapublicPublicRoute,
  } as any)
const PadavaliauthAuthAnalyticsIndexRoute =
  PadavaliauthAuthAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => PadavaliauthAuthRoute,
  } as any)
const PadavaliauthAuthBatch_managerIndexRoute =
  PadavaliauthAuthBatch_managerIndexRouteImport.update({
    id: '/batch_manager/',
    path: '/batch_manager/',
    getParentRoute: () => PadavaliauthAuthRoute,
  } as any)
const PadavaliauthAuthEditIdRoute = PadavaliauthAuthEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => PadavaliauthAuthRoute,
} as any)
const PadavaliauthAuthListIndexRoute =
  PadavaliauthAuthListIndexRouteImport.update({
    id: '/list/',
    path: '/list/',
    getParentRoute: () => PadavaliauthAuthRoute,
  } as any)
const PadavaliauthAuthSchedulesIndexRoute =
  PadavaliauthAuthSchedulesIndexRouteImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => PadavaliauthAuthRoute,
  } as any)
const PadavalipublicPublicArchivedId_uuidRoute =
  PadavalipublicPublicArchivedId_uuidRouteImport.update({
    id: '/archived/$id_uuid',
    path: '/archived/$id_uuid',
    getParentRoute: () => PadavalipublicPublicRoute,
  } as any)
const PadavalipublicPublicPuzzleSlugRoute =
  PadavalipublicPublicPuzzleSlugRouteImport.update({
    id: '/puzzle/$slug',
    path: '/puzzle/$slug',
    getParentRoute: () => PadavalipublicPublicRoute,
  } as any)
const PadavalipublicPublicPuzzlesIndexRoute =
  PadavalipublicPublicPuzzlesIndexRouteImport.update({
    id: '/puzzles/',
    path: '/puzzles/',
    getParentRoute: () => PadavalipublicPublicRoute,
  } as any)
const PadavalipublicPublicViewId_slugRoute =
  PadavalipublicPublicViewId_slugRouteImport.update({
    id: '/view/$id_slug',
    path: '/view/$id_slug',
    getParentRoute: () => PadavalipublicPublicRoute,
  } as any)
const PadajalaauthAuthSchedulesAddIndexRoute =
  PadajalaauthAuthSchedulesAddIndexRouteImport.update({
    id: '/schedules/add/',
    path: '/schedules/add/',
    getParentRoute: () => PadajalaauthAuthRoute,
  } as any)
const PadajalaauthAuthSchedulesEditIdRoute =
  PadajalaauthAuthSchedulesEditIdRouteImport.update({
    id: '/schedules/edit/$id',
    path: '/schedules/edit/$id',
    getParentRoute: () => PadajalaauthAuthRoute,
  } as any)
const PadavaliauthAuthSchedulesAddIndexRoute =
  PadavaliauthAuthSchedulesAddIndexRouteImport.update({
    id: '/schedules/add/',
    path: '/schedules/add/',
    getParentRoute: () => PadavaliauthAuthRoute,
  } as any)
const PadavaliauthAuthSchedulesEditIdRoute =
  PadavaliauthAuthSchedulesEditIdRouteImport.update({
    id: '/schedules/edit/$id',
    path: '/schedules/edit/$id',
    getParentRoute: () => PadavaliauthAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/padajala': typeof PadajalaRouteRouteWithChildren
  '/padavali': typeof PadavaliRouteRouteWithChildren
  '/crossword/$': typeof CrosswordSplatRoute
  '/api/qstash/new_puzzle_notification': typeof ApiQstashNew_puzzle_notificationRoute
  '/api/qstash/save_ai_batch_results': typeof ApiQstashSave_ai_batch_resultsRoute
  '/api/qstash/schedule_listing': typeof ApiQstashSchedule_listingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/qstash/crossword/schedule_listing': typeof ApiQstashCrosswordSchedule_listingRoute
  '/padajala/$slug': typeof PadajalapublicPublicSlugRoute
  '/padavali/$slug': typeof PadavalipublicPublicSlugRoute
  '/padajala/': typeof PadajalapublicPublicIndexRoute
  '/padavali/': typeof PadavalipublicPublicIndexRoute
  '/padajala/edit/$id': typeof PadajalaauthAuthEditIdRoute
  '/padajala/archived/$id_uuid': typeof PadajalapublicPublicArchivedId_uuidRoute
  '/padajala/puzzle/$slug': typeof PadajalapublicPublicPuzzleSlugRoute
  '/padajala/view/$id_slug': typeof PadajalapublicPublicViewId_slugRoute
  '/padavali/edit/$id': typeof PadavaliauthAuthEditIdRoute
  '/padavali/archived/$id_uuid': typeof PadavalipublicPublicArchivedId_uuidRoute
  '/padavali/puzzle/$slug': typeof PadavalipublicPublicPuzzleSlugRoute
  '/padavali/view/$id_slug': typeof PadavalipublicPublicViewId_slugRoute
  '/padajala/analytics/': typeof PadajalaauthAuthAnalyticsIndexRoute
  '/padajala/batch_manager/': typeof PadajalaauthAuthBatch_managerIndexRoute
  '/padajala/list/': typeof PadajalaauthAuthListIndexRoute
  '/padajala/schedules/': typeof PadajalaauthAuthSchedulesIndexRoute
  '/padajala/puzzles/': typeof PadajalapublicPublicPuzzlesIndexRoute
  '/padavali/analytics/': typeof PadavaliauthAuthAnalyticsIndexRoute
  '/padavali/batch_manager/': typeof PadavaliauthAuthBatch_managerIndexRoute
  '/padavali/list/': typeof PadavaliauthAuthListIndexRoute
  '/padavali/schedules/': typeof PadavaliauthAuthSchedulesIndexRoute
  '/padavali/puzzles/': typeof PadavalipublicPublicPuzzlesIndexRoute
  '/padajala/schedules/edit/$id': typeof PadajalaauthAuthSchedulesEditIdRoute
  '/padavali/schedules/edit/$id': typeof PadavaliauthAuthSchedulesEditIdRoute
  '/padajala/schedules/add/': typeof PadajalaauthAuthSchedulesAddIndexRoute
  '/padavali/schedules/add/': typeof PadavaliauthAuthSchedulesAddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/padajala': typeof PadajalapublicPublicIndexRoute
  '/padavali': typeof PadavalipublicPublicIndexRoute
  '/crossword/$': typeof CrosswordSplatRoute
  '/api/qstash/new_puzzle_notification': typeof ApiQstashNew_puzzle_notificationRoute
  '/api/qstash/save_ai_batch_results': typeof ApiQstashSave_ai_batch_resultsRoute
  '/api/qstash/schedule_listing': typeof ApiQstashSchedule_listingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/qstash/crossword/schedule_listing': typeof ApiQstashCrosswordSchedule_listingRoute
  '/padajala/$slug': typeof PadajalapublicPublicSlugRoute
  '/padavali/$slug': typeof PadavalipublicPublicSlugRoute
  '/padajala/edit/$id': typeof PadajalaauthAuthEditIdRoute
  '/padajala/archived/$id_uuid': typeof PadajalapublicPublicArchivedId_uuidRoute
  '/padajala/puzzle/$slug': typeof PadajalapublicPublicPuzzleSlugRoute
  '/padajala/view/$id_slug': typeof PadajalapublicPublicViewId_slugRoute
  '/padavali/edit/$id': typeof PadavaliauthAuthEditIdRoute
  '/padavali/archived/$id_uuid': typeof PadavalipublicPublicArchivedId_uuidRoute
  '/padavali/puzzle/$slug': typeof PadavalipublicPublicPuzzleSlugRoute
  '/padavali/view/$id_slug': typeof PadavalipublicPublicViewId_slugRoute
  '/padajala/analytics': typeof PadajalaauthAuthAnalyticsIndexRoute
  '/padajala/batch_manager': typeof PadajalaauthAuthBatch_managerIndexRoute
  '/padajala/list': typeof PadajalaauthAuthListIndexRoute
  '/padajala/schedules': typeof PadajalaauthAuthSchedulesIndexRoute
  '/padajala/puzzles': typeof PadajalapublicPublicPuzzlesIndexRoute
  '/padavali/analytics': typeof PadavaliauthAuthAnalyticsIndexRoute
  '/padavali/batch_manager': typeof PadavaliauthAuthBatch_managerIndexRoute
  '/padavali/list': typeof PadavaliauthAuthListIndexRoute
  '/padavali/schedules': typeof PadavaliauthAuthSchedulesIndexRoute
  '/padavali/puzzles': typeof PadavalipublicPublicPuzzlesIndexRoute
  '/padajala/schedules/edit/$id': typeof PadajalaauthAuthSchedulesEditIdRoute
  '/padavali/schedules/edit/$id': typeof PadavaliauthAuthSchedulesEditIdRoute
  '/padajala/schedules/add': typeof PadajalaauthAuthSchedulesAddIndexRoute
  '/padavali/schedules/add': typeof PadavaliauthAuthSchedulesAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/padajala': typeof PadajalaRouteRouteWithChildren
  '/padavali': typeof PadavaliRouteRouteWithChildren
  '/crossword/$': typeof CrosswordSplatRoute
  '/api/qstash/new_puzzle_notification': typeof ApiQstashNew_puzzle_notificationRoute
  '/api/qstash/save_ai_batch_results': typeof ApiQstashSave_ai_batch_resultsRoute
  '/api/qstash/schedule_listing': typeof ApiQstashSchedule_listingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/padajala/(auth)/_auth': typeof PadajalaauthAuthRouteWithChildren
  '/padajala/(public)/_public': typeof PadajalapublicPublicRouteWithChildren
  '/padavali/(auth)/_auth': typeof PadavaliauthAuthRouteWithChildren
  '/padavali/(public)/_public': typeof PadavalipublicPublicRouteWithChildren
  '/api/qstash/crossword/schedule_listing': typeof ApiQstashCrosswordSchedule_listingRoute
  '/padajala/(public)/_public/$slug': typeof PadajalapublicPublicSlugRoute
  '/padavali/(public)/_public/$slug': typeof PadavalipublicPublicSlugRoute
  '/padajala/(public)/_public/': typeof PadajalapublicPublicIndexRoute
  '/padavali/(public)/_public/': typeof PadavalipublicPublicIndexRoute
  '/padajala/(auth)/_auth/edit/$id': typeof PadajalaauthAuthEditIdRoute
  '/padajala/(public)/_public/archived/$id_uuid': typeof PadajalapublicPublicArchivedId_uuidRoute
  '/padajala/(public)/_public/puzzle/$slug': typeof PadajalapublicPublicPuzzleSlugRoute
  '/padajala/(public)/_public/view/$id_slug': typeof PadajalapublicPublicViewId_slugRoute
  '/padavali/(auth)/_auth/edit/$id': typeof PadavaliauthAuthEditIdRoute
  '/padavali/(public)/_public/archived/$id_uuid': typeof PadavalipublicPublicArchivedId_uuidRoute
  '/padavali/(public)/_public/puzzle/$slug': typeof PadavalipublicPublicPuzzleSlugRoute
  '/padavali/(public)/_public/view/$id_slug': typeof PadavalipublicPublicViewId_slugRoute
  '/padajala/(auth)/_auth/analytics/': typeof PadajalaauthAuthAnalyticsIndexRoute
  '/padajala/(auth)/_auth/batch_manager/': typeof PadajalaauthAuthBatch_managerIndexRoute
  '/padajala/(auth)/_auth/list/': typeof PadajalaauthAuthListIndexRoute
  '/padajala/(auth)/_auth/schedules/': typeof PadajalaauthAuthSchedulesIndexRoute
  '/padajala/(public)/_public/puzzles/': typeof PadajalapublicPublicPuzzlesIndexRoute
  '/padavali/(auth)/_auth/analytics/': typeof PadavaliauthAuthAnalyticsIndexRoute
  '/padavali/(auth)/_auth/batch_manager/': typeof PadavaliauthAuthBatch_managerIndexRoute
  '/padavali/(auth)/_auth/list/': typeof PadavaliauthAuthListIndexRoute
  '/padavali/(auth)/_auth/schedules/': typeof PadavaliauthAuthSchedulesIndexRoute
  '/padavali/(public)/_public/puzzles/': typeof PadavalipublicPublicPuzzlesIndexRoute
  '/padajala/(auth)/_auth/schedules/edit/$id': typeof PadajalaauthAuthSchedulesEditIdRoute
  '/padavali/(auth)/_auth/schedules/edit/$id': typeof PadavaliauthAuthSchedulesEditIdRoute
  '/padajala/(auth)/_auth/schedules/add/': typeof PadajalaauthAuthSchedulesAddIndexRoute
  '/padavali/(auth)/_auth/schedules/add/': typeof PadavaliauthAuthSchedulesAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/padajala'
    | '/padavali'
    | '/crossword/$'
    | '/api/qstash/new_puzzle_notification'
    | '/api/qstash/save_ai_batch_results'
    | '/api/qstash/schedule_listing'
    | '/api/trpc/$'
    | '/api/qstash/crossword/schedule_listing'
    | '/padajala/$slug'
    | '/padavali/$slug'
    | '/padajala/'
    | '/padavali/'
    | '/padajala/edit/$id'
    | '/padajala/archived/$id_uuid'
    | '/padajala/puzzle/$slug'
    | '/padajala/view/$id_slug'
    | '/padavali/edit/$id'
    | '/padavali/archived/$id_uuid'
    | '/padavali/puzzle/$slug'
    | '/padavali/view/$id_slug'
    | '/padajala/analytics/'
    | '/padajala/batch_manager/'
    | '/padajala/list/'
    | '/padajala/schedules/'
    | '/padajala/puzzles/'
    | '/padavali/analytics/'
    | '/padavali/batch_manager/'
    | '/padavali/list/'
    | '/padavali/schedules/'
    | '/padavali/puzzles/'
    | '/padajala/schedules/edit/$id'
    | '/padavali/schedules/edit/$id'
    | '/padajala/schedules/add/'
    | '/padavali/schedules/add/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/padajala'
    | '/padavali'
    | '/crossword/$'
    | '/api/qstash/new_puzzle_notification'
    | '/api/qstash/save_ai_batch_results'
    | '/api/qstash/schedule_listing'
    | '/api/trpc/$'
    | '/api/qstash/crossword/schedule_listing'
    | '/padajala/$slug'
    | '/padavali/$slug'
    | '/padajala/edit/$id'
    | '/padajala/archived/$id_uuid'
    | '/padajala/puzzle/$slug'
    | '/padajala/view/$id_slug'
    | '/padavali/edit/$id'
    | '/padavali/archived/$id_uuid'
    | '/padavali/puzzle/$slug'
    | '/padavali/view/$id_slug'
    | '/padajala/analytics'
    | '/padajala/batch_manager'
    | '/padajala/list'
    | '/padajala/schedules'
    | '/padajala/puzzles'
    | '/padavali/analytics'
    | '/padavali/batch_manager'
    | '/padavali/list'
    | '/padavali/schedules'
    | '/padavali/puzzles'
    | '/padajala/schedules/edit/$id'
    | '/padavali/schedules/edit/$id'
    | '/padajala/schedules/add'
    | '/padavali/schedules/add'
  id:
    | '__root__'
    | '/'
    | '/padajala'
    | '/padavali'
    | '/crossword/$'
    | '/api/qstash/new_puzzle_notification'
    | '/api/qstash/save_ai_batch_results'
    | '/api/qstash/schedule_listing'
    | '/api/trpc/$'
    | '/padajala/(auth)/_auth'
    | '/padajala/(public)/_public'
    | '/padavali/(auth)/_auth'
    | '/padavali/(public)/_public'
    | '/api/qstash/crossword/schedule_listing'
    | '/padajala/(public)/_public/$slug'
    | '/padavali/(public)/_public/$slug'
    | '/padajala/(public)/_public/'
    | '/padavali/(public)/_public/'
    | '/padajala/(auth)/_auth/edit/$id'
    | '/padajala/(public)/_public/archived/$id_uuid'
    | '/padajala/(public)/_public/puzzle/$slug'
    | '/padajala/(public)/_public/view/$id_slug'
    | '/padavali/(auth)/_auth/edit/$id'
    | '/padavali/(public)/_public/archived/$id_uuid'
    | '/padavali/(public)/_public/puzzle/$slug'
    | '/padavali/(public)/_public/view/$id_slug'
    | '/padajala/(auth)/_auth/analytics/'
    | '/padajala/(auth)/_auth/batch_manager/'
    | '/padajala/(auth)/_auth/list/'
    | '/padajala/(auth)/_auth/schedules/'
    | '/padajala/(public)/_public/puzzles/'
    | '/padavali/(auth)/_auth/analytics/'
    | '/padavali/(auth)/_auth/batch_manager/'
    | '/padavali/(auth)/_auth/list/'
    | '/padavali/(auth)/_auth/schedules/'
    | '/padavali/(public)/_public/puzzles/'
    | '/padajala/(auth)/_auth/schedules/edit/$id'
    | '/padavali/(auth)/_auth/schedules/edit/$id'
    | '/padajala/(auth)/_auth/schedules/add/'
    | '/padavali/(auth)/_auth/schedules/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PadajalaRouteRoute: typeof PadajalaRouteRouteWithChildren
  PadavaliRouteRoute: typeof PadavaliRouteRouteWithChildren
  CrosswordSplatRoute: typeof CrosswordSplatRoute
  ApiQstashNew_puzzle_notificationRoute: typeof ApiQstashNew_puzzle_notificationRoute
  ApiQstashSave_ai_batch_resultsRoute: typeof ApiQstashSave_ai_batch_resultsRoute
  ApiQstashSchedule_listingRoute: typeof ApiQstashSchedule_listingRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiQstashCrosswordSchedule_listingRoute: typeof ApiQstashCrosswordSchedule_listingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/padajala': {
      id: '/padajala'
      path: '/padajala'
      fullPath: '/padajala'
      preLoaderRoute: typeof PadajalaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/padavali': {
      id: '/padavali'
      path: '/padavali'
      fullPath: '/padavali'
      preLoaderRoute: typeof PadavaliRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crossword/$': {
      id: '/crossword/$'
      path: '/crossword/$'
      fullPath: '/crossword/$'
      preLoaderRoute: typeof CrosswordSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qstash/new_puzzle_notification': {
      id: '/api/qstash/new_puzzle_notification'
      path: '/api/qstash/new_puzzle_notification'
      fullPath: '/api/qstash/new_puzzle_notification'
      preLoaderRoute: typeof ApiQstashNew_puzzle_notificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qstash/save_ai_batch_results': {
      id: '/api/qstash/save_ai_batch_results'
      path: '/api/qstash/save_ai_batch_results'
      fullPath: '/api/qstash/save_ai_batch_results'
      preLoaderRoute: typeof ApiQstashSave_ai_batch_resultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qstash/schedule_listing': {
      id: '/api/qstash/schedule_listing'
      path: '/api/qstash/schedule_listing'
      fullPath: '/api/qstash/schedule_listing'
      preLoaderRoute: typeof ApiQstashSchedule_listingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/padajala/(auth)/_auth': {
      id: '/padajala/(auth)/_auth'
      path: ''
      fullPath: '/padajala'
      preLoaderRoute: typeof PadajalaauthAuthRouteImport
      parentRoute: typeof PadajalaRouteRoute
    }
    '/padajala/(public)/_public': {
      id: '/padajala/(public)/_public'
      path: ''
      fullPath: '/padajala'
      preLoaderRoute: typeof PadajalapublicPublicRouteImport
      parentRoute: typeof PadajalaRouteRoute
    }
    '/padavali/(auth)/_auth': {
      id: '/padavali/(auth)/_auth'
      path: ''
      fullPath: '/padavali'
      preLoaderRoute: typeof PadavaliauthAuthRouteImport
      parentRoute: typeof PadavaliRouteRoute
    }
    '/padavali/(public)/_public': {
      id: '/padavali/(public)/_public'
      path: ''
      fullPath: '/padavali'
      preLoaderRoute: typeof PadavalipublicPublicRouteImport
      parentRoute: typeof PadavaliRouteRoute
    }
    '/api/qstash/crossword/schedule_listing': {
      id: '/api/qstash/crossword/schedule_listing'
      path: '/api/qstash/crossword/schedule_listing'
      fullPath: '/api/qstash/crossword/schedule_listing'
      preLoaderRoute: typeof ApiQstashCrosswordSchedule_listingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/padajala/(public)/_public/': {
      id: '/padajala/(public)/_public/'
      path: '/'
      fullPath: '/padajala/'
      preLoaderRoute: typeof PadajalapublicPublicIndexRouteImport
      parentRoute: typeof PadajalapublicPublicRoute
    }
    '/padajala/(public)/_public/$slug': {
      id: '/padajala/(public)/_public/$slug'
      path: '/$slug'
      fullPath: '/padajala/$slug'
      preLoaderRoute: typeof PadajalapublicPublicSlugRouteImport
      parentRoute: typeof PadajalapublicPublicRoute
    }
    '/padavali/(public)/_public/': {
      id: '/padavali/(public)/_public/'
      path: '/'
      fullPath: '/padavali/'
      preLoaderRoute: typeof PadavalipublicPublicIndexRouteImport
      parentRoute: typeof PadavalipublicPublicRoute
    }
    '/padavali/(public)/_public/$slug': {
      id: '/padavali/(public)/_public/$slug'
      path: '/$slug'
      fullPath: '/padavali/$slug'
      preLoaderRoute: typeof PadavalipublicPublicSlugRouteImport
      parentRoute: typeof PadavalipublicPublicRoute
    }
    '/padajala/(auth)/_auth/analytics/': {
      id: '/padajala/(auth)/_auth/analytics/'
      path: '/analytics'
      fullPath: '/padajala/analytics/'
      preLoaderRoute: typeof PadajalaauthAuthAnalyticsIndexRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padajala/(auth)/_auth/batch_manager/': {
      id: '/padajala/(auth)/_auth/batch_manager/'
      path: '/batch_manager'
      fullPath: '/padajala/batch_manager/'
      preLoaderRoute: typeof PadajalaauthAuthBatch_managerIndexRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padajala/(auth)/_auth/edit/$id': {
      id: '/padajala/(auth)/_auth/edit/$id'
      path: '/edit/$id'
      fullPath: '/padajala/edit/$id'
      preLoaderRoute: typeof PadajalaauthAuthEditIdRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padajala/(auth)/_auth/list/': {
      id: '/padajala/(auth)/_auth/list/'
      path: '/list'
      fullPath: '/padajala/list/'
      preLoaderRoute: typeof PadajalaauthAuthListIndexRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padajala/(auth)/_auth/schedules/': {
      id: '/padajala/(auth)/_auth/schedules/'
      path: '/schedules'
      fullPath: '/padajala/schedules/'
      preLoaderRoute: typeof PadajalaauthAuthSchedulesIndexRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padajala/(public)/_public/archived/$id_uuid': {
      id: '/padajala/(public)/_public/archived/$id_uuid'
      path: '/archived/$id_uuid'
      fullPath: '/padajala/archived/$id_uuid'
      preLoaderRoute: typeof PadajalapublicPublicArchivedId_uuidRouteImport
      parentRoute: typeof PadajalapublicPublicRoute
    }
    '/padajala/(public)/_public/puzzle/$slug': {
      id: '/padajala/(public)/_public/puzzle/$slug'
      path: '/puzzle/$slug'
      fullPath: '/padajala/puzzle/$slug'
      preLoaderRoute: typeof PadajalapublicPublicPuzzleSlugRouteImport
      parentRoute: typeof PadajalapublicPublicRoute
    }
    '/padajala/(public)/_public/puzzles/': {
      id: '/padajala/(public)/_public/puzzles/'
      path: '/puzzles'
      fullPath: '/padajala/puzzles/'
      preLoaderRoute: typeof PadajalapublicPublicPuzzlesIndexRouteImport
      parentRoute: typeof PadajalapublicPublicRoute
    }
    '/padajala/(public)/_public/view/$id_slug': {
      id: '/padajala/(public)/_public/view/$id_slug'
      path: '/view/$id_slug'
      fullPath: '/padajala/view/$id_slug'
      preLoaderRoute: typeof PadajalapublicPublicViewId_slugRouteImport
      parentRoute: typeof PadajalapublicPublicRoute
    }
    '/padavali/(auth)/_auth/analytics/': {
      id: '/padavali/(auth)/_auth/analytics/'
      path: '/analytics'
      fullPath: '/padavali/analytics/'
      preLoaderRoute: typeof PadavaliauthAuthAnalyticsIndexRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
    '/padavali/(auth)/_auth/batch_manager/': {
      id: '/padavali/(auth)/_auth/batch_manager/'
      path: '/batch_manager'
      fullPath: '/padavali/batch_manager/'
      preLoaderRoute: typeof PadavaliauthAuthBatch_managerIndexRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
    '/padavali/(auth)/_auth/edit/$id': {
      id: '/padavali/(auth)/_auth/edit/$id'
      path: '/edit/$id'
      fullPath: '/padavali/edit/$id'
      preLoaderRoute: typeof PadavaliauthAuthEditIdRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
    '/padavali/(auth)/_auth/list/': {
      id: '/padavali/(auth)/_auth/list/'
      path: '/list'
      fullPath: '/padavali/list/'
      preLoaderRoute: typeof PadavaliauthAuthListIndexRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
    '/padavali/(auth)/_auth/schedules/': {
      id: '/padavali/(auth)/_auth/schedules/'
      path: '/schedules'
      fullPath: '/padavali/schedules/'
      preLoaderRoute: typeof PadavaliauthAuthSchedulesIndexRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
    '/padavali/(public)/_public/archived/$id_uuid': {
      id: '/padavali/(public)/_public/archived/$id_uuid'
      path: '/archived/$id_uuid'
      fullPath: '/padavali/archived/$id_uuid'
      preLoaderRoute: typeof PadavalipublicPublicArchivedId_uuidRouteImport
      parentRoute: typeof PadavalipublicPublicRoute
    }
    '/padavali/(public)/_public/puzzle/$slug': {
      id: '/padavali/(public)/_public/puzzle/$slug'
      path: '/puzzle/$slug'
      fullPath: '/padavali/puzzle/$slug'
      preLoaderRoute: typeof PadavalipublicPublicPuzzleSlugRouteImport
      parentRoute: typeof PadavalipublicPublicRoute
    }
    '/padavali/(public)/_public/puzzles/': {
      id: '/padavali/(public)/_public/puzzles/'
      path: '/puzzles'
      fullPath: '/padavali/puzzles/'
      preLoaderRoute: typeof PadavalipublicPublicPuzzlesIndexRouteImport
      parentRoute: typeof PadavalipublicPublicRoute
    }
    '/padavali/(public)/_public/view/$id_slug': {
      id: '/padavali/(public)/_public/view/$id_slug'
      path: '/view/$id_slug'
      fullPath: '/padavali/view/$id_slug'
      preLoaderRoute: typeof PadavalipublicPublicViewId_slugRouteImport
      parentRoute: typeof PadavalipublicPublicRoute
    }
    '/padajala/(auth)/_auth/schedules/add/': {
      id: '/padajala/(auth)/_auth/schedules/add/'
      path: '/schedules/add'
      fullPath: '/padajala/schedules/add/'
      preLoaderRoute: typeof PadajalaauthAuthSchedulesAddIndexRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padajala/(auth)/_auth/schedules/edit/$id': {
      id: '/padajala/(auth)/_auth/schedules/edit/$id'
      path: '/schedules/edit/$id'
      fullPath: '/padajala/schedules/edit/$id'
      preLoaderRoute: typeof PadajalaauthAuthSchedulesEditIdRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padavali/(auth)/_auth/schedules/add/': {
      id: '/padavali/(auth)/_auth/schedules/add/'
      path: '/schedules/add'
      fullPath: '/padavali/schedules/add/'
      preLoaderRoute: typeof PadavaliauthAuthSchedulesAddIndexRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
    '/padavali/(auth)/_auth/schedules/edit/$id': {
      id: '/padavali/(auth)/_auth/schedules/edit/$id'
      path: '/schedules/edit/$id'
      fullPath: '/padavali/schedules/edit/$id'
      preLoaderRoute: typeof PadavaliauthAuthSchedulesEditIdRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
  }
}

interface PadajalaauthAuthRouteChildren {
  PadajalaauthAuthEditIdRoute: typeof PadajalaauthAuthEditIdRoute
  PadajalaauthAuthAnalyticsIndexRoute: typeof PadajalaauthAuthAnalyticsIndexRoute
  PadajalaauthAuthBatch_managerIndexRoute: typeof PadajalaauthAuthBatch_managerIndexRoute
  PadajalaauthAuthListIndexRoute: typeof PadajalaauthAuthListIndexRoute
  PadajalaauthAuthSchedulesIndexRoute: typeof PadajalaauthAuthSchedulesIndexRoute
  PadajalaauthAuthSchedulesEditIdRoute: typeof PadajalaauthAuthSchedulesEditIdRoute
  PadajalaauthAuthSchedulesAddIndexRoute: typeof PadajalaauthAuthSchedulesAddIndexRoute
}

const PadajalaauthAuthRouteChildren: PadajalaauthAuthRouteChildren = {
  PadajalaauthAuthEditIdRoute: PadajalaauthAuthEditIdRoute,
  PadajalaauthAuthAnalyticsIndexRoute: PadajalaauthAuthAnalyticsIndexRoute,
  PadajalaauthAuthBatch_managerIndexRoute:
    PadajalaauthAuthBatch_managerIndexRoute,
  PadajalaauthAuthListIndexRoute: PadajalaauthAuthListIndexRoute,
  PadajalaauthAuthSchedulesIndexRoute: PadajalaauthAuthSchedulesIndexRoute,
  PadajalaauthAuthSchedulesEditIdRoute: PadajalaauthAuthSchedulesEditIdRoute,
  PadajalaauthAuthSchedulesAddIndexRoute:
    PadajalaauthAuthSchedulesAddIndexRoute,
}

const PadajalaauthAuthRouteWithChildren =
  PadajalaauthAuthRoute._addFileChildren(PadajalaauthAuthRouteChildren)

interface PadajalapublicPublicRouteChildren {
  PadajalapublicPublicSlugRoute: typeof PadajalapublicPublicSlugRoute
  PadajalapublicPublicIndexRoute: typeof PadajalapublicPublicIndexRoute
  PadajalapublicPublicArchivedId_uuidRoute: typeof PadajalapublicPublicArchivedId_uuidRoute
  PadajalapublicPublicPuzzleSlugRoute: typeof PadajalapublicPublicPuzzleSlugRoute
  PadajalapublicPublicViewId_slugRoute: typeof PadajalapublicPublicViewId_slugRoute
  PadajalapublicPublicPuzzlesIndexRoute: typeof PadajalapublicPublicPuzzlesIndexRoute
}

const PadajalapublicPublicRouteChildren: PadajalapublicPublicRouteChildren = {
  PadajalapublicPublicSlugRoute: PadajalapublicPublicSlugRoute,
  PadajalapublicPublicIndexRoute: PadajalapublicPublicIndexRoute,
  PadajalapublicPublicArchivedId_uuidRoute:
    PadajalapublicPublicArchivedId_uuidRoute,
  PadajalapublicPublicPuzzleSlugRoute: PadajalapublicPublicPuzzleSlugRoute,
  PadajalapublicPublicViewId_slugRoute: PadajalapublicPublicViewId_slugRoute,
  PadajalapublicPublicPuzzlesIndexRoute: PadajalapublicPublicPuzzlesIndexRoute,
}

const PadajalapublicPublicRouteWithChildren =
  PadajalapublicPublicRoute._addFileChildren(PadajalapublicPublicRouteChildren)

interface PadajalaRouteRouteChildren {
  PadajalaauthAuthRoute: typeof PadajalaauthAuthRouteWithChildren
  PadajalapublicPublicRoute: typeof PadajalapublicPublicRouteWithChildren
}

const PadajalaRouteRouteChildren: PadajalaRouteRouteChildren = {
  PadajalaauthAuthRoute: PadajalaauthAuthRouteWithChildren,
  PadajalapublicPublicRoute: PadajalapublicPublicRouteWithChildren,
}

const PadajalaRouteRouteWithChildren = PadajalaRouteRoute._addFileChildren(
  PadajalaRouteRouteChildren,
)

interface PadavaliauthAuthRouteChildren {
  PadavaliauthAuthEditIdRoute: typeof PadavaliauthAuthEditIdRoute
  PadavaliauthAuthAnalyticsIndexRoute: typeof PadavaliauthAuthAnalyticsIndexRoute
  PadavaliauthAuthBatch_managerIndexRoute: typeof PadavaliauthAuthBatch_managerIndexRoute
  PadavaliauthAuthListIndexRoute: typeof PadavaliauthAuthListIndexRoute
  PadavaliauthAuthSchedulesIndexRoute: typeof PadavaliauthAuthSchedulesIndexRoute
  PadavaliauthAuthSchedulesEditIdRoute: typeof PadavaliauthAuthSchedulesEditIdRoute
  PadavaliauthAuthSchedulesAddIndexRoute: typeof PadavaliauthAuthSchedulesAddIndexRoute
}

const PadavaliauthAuthRouteChildren: PadavaliauthAuthRouteChildren = {
  PadavaliauthAuthEditIdRoute: PadavaliauthAuthEditIdRoute,
  PadavaliauthAuthAnalyticsIndexRoute: PadavaliauthAuthAnalyticsIndexRoute,
  PadavaliauthAuthBatch_managerIndexRoute:
    PadavaliauthAuthBatch_managerIndexRoute,
  PadavaliauthAuthListIndexRoute: PadavaliauthAuthListIndexRoute,
  PadavaliauthAuthSchedulesIndexRoute: PadavaliauthAuthSchedulesIndexRoute,
  PadavaliauthAuthSchedulesEditIdRoute: PadavaliauthAuthSchedulesEditIdRoute,
  PadavaliauthAuthSchedulesAddIndexRoute:
    PadavaliauthAuthSchedulesAddIndexRoute,
}

const PadavaliauthAuthRouteWithChildren =
  PadavaliauthAuthRoute._addFileChildren(PadavaliauthAuthRouteChildren)

interface PadavalipublicPublicRouteChildren {
  PadavalipublicPublicSlugRoute: typeof PadavalipublicPublicSlugRoute
  PadavalipublicPublicIndexRoute: typeof PadavalipublicPublicIndexRoute
  PadavalipublicPublicArchivedId_uuidRoute: typeof PadavalipublicPublicArchivedId_uuidRoute
  PadavalipublicPublicPuzzleSlugRoute: typeof PadavalipublicPublicPuzzleSlugRoute
  PadavalipublicPublicViewId_slugRoute: typeof PadavalipublicPublicViewId_slugRoute
  PadavalipublicPublicPuzzlesIndexRoute: typeof PadavalipublicPublicPuzzlesIndexRoute
}

const PadavalipublicPublicRouteChildren: PadavalipublicPublicRouteChildren = {
  PadavalipublicPublicSlugRoute: PadavalipublicPublicSlugRoute,
  PadavalipublicPublicIndexRoute: PadavalipublicPublicIndexRoute,
  PadavalipublicPublicArchivedId_uuidRoute:
    PadavalipublicPublicArchivedId_uuidRoute,
  PadavalipublicPublicPuzzleSlugRoute: PadavalipublicPublicPuzzleSlugRoute,
  PadavalipublicPublicViewId_slugRoute: PadavalipublicPublicViewId_slugRoute,
  PadavalipublicPublicPuzzlesIndexRoute: PadavalipublicPublicPuzzlesIndexRoute,
}

const PadavalipublicPublicRouteWithChildren =
  PadavalipublicPublicRoute._addFileChildren(PadavalipublicPublicRouteChildren)

interface PadavaliRouteRouteChildren {
  PadavaliauthAuthRoute: typeof PadavaliauthAuthRouteWithChildren
  PadavalipublicPublicRoute: typeof PadavalipublicPublicRouteWithChildren
}

const PadavaliRouteRouteChildren: PadavaliRouteRouteChildren = {
  PadavaliauthAuthRoute: PadavaliauthAuthRouteWithChildren,
  PadavalipublicPublicRoute: PadavalipublicPublicRouteWithChildren,
}

const PadavaliRouteRouteWithChildren = PadavaliRouteRoute._addFileChildren(
  PadavaliRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PadajalaRouteRoute: PadajalaRouteRouteWithChildren,
  PadavaliRouteRoute: PadavaliRouteRouteWithChildren,
  CrosswordSplatRoute: CrosswordSplatRoute,
  ApiQstashNew_puzzle_notificationRoute: ApiQstashNew_puzzle_notificationRoute,
  ApiQstashSave_ai_batch_resultsRoute: ApiQstashSave_ai_batch_resultsRoute,
  ApiQstashSchedule_listingRoute: ApiQstashSchedule_listingRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiQstashCrosswordSchedule_listingRoute:
    ApiQstashCrosswordSchedule_listingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
