/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HubRouteImport } from './routes/_hub'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AnveshiRouteRouteImport } from './routes/anveshi/route'
import { Route as BhramitARouteRouteImport } from './routes/bhramitA/route'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DvayiRouteRouteImport } from './routes/dvayi/route'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as PadajalaRouteRouteImport } from './routes/padajala/route'
import { Route as PadavaliRouteRouteImport } from './routes/padavali/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as Sitemap0DotxmlRouteImport } from './routes/sitemap-0[.]xml'
import { Route as Sitemap1DotxmlRouteImport } from './routes/sitemap-1[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as SurUpaRouteRouteImport } from './routes/surUpa/route'
import { Route as HubIndexRouteImport } from './routes/_hub/index'
import { Route as HubPuzzlesRouteImport } from './routes/_hub/puzzles'
import { Route as CollectionsListRouteImport } from './routes/collections/list'
import { Route as CrosswordSplatRouteImport } from './routes/crossword.$'
import { Route as TagsListRouteImport } from './routes/tags/list'
import { Route as HubCollectionsSlugRouteImport } from './routes/_hub/collections/$slug'
import { Route as AnveshiauthAuthRouteImport } from './routes/anveshi/(auth)/_auth'
import { Route as AnveshipublicPublicRouteImport } from './routes/anveshi/(public)/_public'
import { Route as ApiQstashNew_puzzle_notificationRouteImport } from './routes/api/qstash/new_puzzle_notification'
import { Route as ApiQstashSave_ai_batch_resultsRouteImport } from './routes/api/qstash/save_ai_batch_results'
import { Route as ApiQstashSchedule_listingRouteImport } from './routes/api/qstash/schedule_listing'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as BhramitAauthAuthRouteImport } from './routes/bhramitA/(auth)/_auth'
import { Route as BhramitApublicPublicRouteImport } from './routes/bhramitA/(public)/_public'
import { Route as CollectionsEditUidRouteImport } from './routes/collections/edit/$uid'
import { Route as DvayiauthAuthRouteImport } from './routes/dvayi/(auth)/_auth'
import { Route as DvayipublicPublicRouteImport } from './routes/dvayi/(public)/_public'
import { Route as PadajalaauthAuthRouteImport } from './routes/padajala/(auth)/_auth'
import { Route as PadajalapublicPublicRouteImport } from './routes/padajala/(public)/_public'
import { Route as PadavaliauthAuthRouteImport } from './routes/padavali/(auth)/_auth'
import { Route as PadavalipublicPublicRouteImport } from './routes/padavali/(public)/_public'
import { Route as SurUpaauthAuthRouteImport } from './routes/surUpa/(auth)/_auth'
import { Route as SurUpapublicPublicRouteImport } from './routes/surUpa/(public)/_public'
import { Route as TagsEditSlugRouteImport } from './routes/tags/edit/$slug'
import { Route as AnveshipublicPublicIndexRouteImport } from './routes/anveshi/(public)/_public/index'
import { Route as AnveshipublicPublicSlugRouteImport } from './routes/anveshi/(public)/_public/$slug'
import { Route as ApiQstashCrosswordSchedule_listingRouteImport } from './routes/api/qstash/crossword/schedule_listing'
import { Route as BhramitApublicPublicIndexRouteImport } from './routes/bhramitA/(public)/_public/index'
import { Route as BhramitApublicPublicSlugRouteImport } from './routes/bhramitA/(public)/_public/$slug'
import { Route as DvayipublicPublicIndexRouteImport } from './routes/dvayi/(public)/_public/index'
import { Route as DvayipublicPublicSlugRouteImport } from './routes/dvayi/(public)/_public/$slug'
import { Route as PadajalapublicPublicIndexRouteImport } from './routes/padajala/(public)/_public/index'
import { Route as PadajalapublicPublicSlugRouteImport } from './routes/padajala/(public)/_public/$slug'
import { Route as PadavalipublicPublicIndexRouteImport } from './routes/padavali/(public)/_public/index'
import { Route as PadavalipublicPublicSlugRouteImport } from './routes/padavali/(public)/_public/$slug'
import { Route as SurUpapublicPublicIndexRouteImport } from './routes/surUpa/(public)/_public/index'
import { Route as SurUpapublicPublicSlugRouteImport } from './routes/surUpa/(public)/_public/$slug'
import { Route as AnveshiauthAuthAnalyticsIndexRouteImport } from './routes/anveshi/(auth)/_auth/analytics/index'
import { Route as AnveshiauthAuthEditIdRouteImport } from './routes/anveshi/(auth)/_auth/edit/$id'
import { Route as AnveshiauthAuthListIndexRouteImport } from './routes/anveshi/(auth)/_auth/list/index'
import { Route as AnveshipublicPublicPuzzlesIndexRouteImport } from './routes/anveshi/(public)/_public/puzzles/index'
import { Route as AnveshipublicPublicViewNano_idRouteImport } from './routes/anveshi/(public)/_public/view/$nano_id'
import { Route as BhramitAauthAuthAnalyticsIndexRouteImport } from './routes/bhramitA/(auth)/_auth/analytics/index'
import { Route as BhramitAauthAuthEditIdRouteImport } from './routes/bhramitA/(auth)/_auth/edit/$id'
import { Route as BhramitAauthAuthListIndexRouteImport } from './routes/bhramitA/(auth)/_auth/list/index'
import { Route as BhramitApublicPublicPuzzlesIndexRouteImport } from './routes/bhramitA/(public)/_public/puzzles/index'
import { Route as BhramitApublicPublicViewNano_idRouteImport } from './routes/bhramitA/(public)/_public/view/$nano_id'
import { Route as DvayiauthAuthAnalyticsIndexRouteImport } from './routes/dvayi/(auth)/_auth/analytics/index'
import { Route as DvayiauthAuthEditIdRouteImport } from './routes/dvayi/(auth)/_auth/edit/$id'
import { Route as DvayiauthAuthListIndexRouteImport } from './routes/dvayi/(auth)/_auth/list/index'
import { Route as DvayipublicPublicPuzzlesIndexRouteImport } from './routes/dvayi/(public)/_public/puzzles/index'
import { Route as DvayipublicPublicViewNano_idRouteImport } from './routes/dvayi/(public)/_public/view/$nano_id'
import { Route as PadajalaauthAuthAnalyticsIndexRouteImport } from './routes/padajala/(auth)/_auth/analytics/index'
import { Route as PadajalaauthAuthBatch_managerIndexRouteImport } from './routes/padajala/(auth)/_auth/batch_manager/index'
import { Route as PadajalaauthAuthCollectionsUidRouteImport } from './routes/padajala/(auth)/_auth/collections/$uid'
import { Route as PadajalaauthAuthEditIdRouteImport } from './routes/padajala/(auth)/_auth/edit/$id'
import { Route as PadajalaauthAuthListIndexRouteImport } from './routes/padajala/(auth)/_auth/list/index'
import { Route as PadajalaauthAuthSchedulesIndexRouteImport } from './routes/padajala/(auth)/_auth/schedules/index'
import { Route as PadajalapublicPublicArchivedId_uuidRouteImport } from './routes/padajala/(public)/_public/archived/$id_uuid'
import { Route as PadajalapublicPublicPuzzleSlugRouteImport } from './routes/padajala/(public)/_public/puzzle/$slug'
import { Route as PadajalapublicPublicPuzzlesIndexRouteImport } from './routes/padajala/(public)/_public/puzzles/index'
import { Route as PadajalapublicPublicViewNano_idRouteImport } from './routes/padajala/(public)/_public/view/$nano_id'
import { Route as PadavaliauthAuthAnalyticsIndexRouteImport } from './routes/padavali/(auth)/_auth/analytics/index'
import { Route as PadavaliauthAuthBatch_managerIndexRouteImport } from './routes/padavali/(auth)/_auth/batch_manager/index'
import { Route as PadavaliauthAuthCollectionsUidRouteImport } from './routes/padavali/(auth)/_auth/collections/$uid'
import { Route as PadavaliauthAuthEditIdRouteImport } from './routes/padavali/(auth)/_auth/edit/$id'
import { Route as PadavaliauthAuthListIndexRouteImport } from './routes/padavali/(auth)/_auth/list/index'
import { Route as PadavaliauthAuthSchedulesIndexRouteImport } from './routes/padavali/(auth)/_auth/schedules/index'
import { Route as PadavalipublicPublicArchivedId_uuidRouteImport } from './routes/padavali/(public)/_public/archived/$id_uuid'
import { Route as PadavalipublicPublicPuzzleSlugRouteImport } from './routes/padavali/(public)/_public/puzzle/$slug'
import { Route as PadavalipublicPublicPuzzlesIndexRouteImport } from './routes/padavali/(public)/_public/puzzles/index'
import { Route as PadavalipublicPublicViewNano_idRouteImport } from './routes/padavali/(public)/_public/view/$nano_id'
import { Route as SurUpaauthAuthAnalyticsIndexRouteImport } from './routes/surUpa/(auth)/_auth/analytics/index'
import { Route as SurUpaauthAuthEditIdRouteImport } from './routes/surUpa/(auth)/_auth/edit/$id'
import { Route as SurUpaauthAuthListIndexRouteImport } from './routes/surUpa/(auth)/_auth/list/index'
import { Route as SurUpapublicPublicPuzzlesIndexRouteImport } from './routes/surUpa/(public)/_public/puzzles/index'
import { Route as SurUpapublicPublicViewNano_idRouteImport } from './routes/surUpa/(public)/_public/view/$nano_id'
import { Route as PadajalaauthAuthSchedulesAddIndexRouteImport } from './routes/padajala/(auth)/_auth/schedules/add/index'
import { Route as PadajalaauthAuthSchedulesEditIdRouteImport } from './routes/padajala/(auth)/_auth/schedules/edit/$id'
import { Route as PadavaliauthAuthSchedulesAddIndexRouteImport } from './routes/padavali/(auth)/_auth/schedules/add/index'
import { Route as PadavaliauthAuthSchedulesEditIdRouteImport } from './routes/padavali/(auth)/_auth/schedules/edit/$id'

const HubRoute = HubRouteImport.update({
  id: '/_hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnveshiRouteRoute = AnveshiRouteRouteImport.update({
  id: '/anveshi',
  path: '/anveshi',
  getParentRoute: () => rootRouteImport,
} as any)
const BhramitARouteRoute = BhramitARouteRouteImport.update({
  id: '/bhramitA',
  path: '/bhramitA',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DvayiRouteRoute = DvayiRouteRouteImport.update({
  id: '/dvayi',
  path: '/dvayi',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const PadajalaRouteRoute = PadajalaRouteRouteImport.update({
  id: '/padajala',
  path: '/padajala',
  getParentRoute: () => rootRouteImport,
} as any)
const PadavaliRouteRoute = PadavaliRouteRouteImport.update({
  id: '/padavali',
  path: '/padavali',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Sitemap0DotxmlRoute = Sitemap0DotxmlRouteImport.update({
  id: '/sitemap-0.xml',
  path: '/sitemap-0.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Sitemap1DotxmlRoute = Sitemap1DotxmlRouteImport.update({
  id: '/sitemap-1.xml',
  path: '/sitemap-1.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SurUpaRouteRoute = SurUpaRouteRouteImport.update({
  id: '/surUpa',
  path: '/surUpa',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubRoute,
} as any)
const HubPuzzlesRoute = HubPuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => HubRoute,
} as any)
const CollectionsListRoute = CollectionsListRouteImport.update({
  id: '/collections/list',
  path: '/collections/list',
  getParentRoute: () => rootRouteImport,
} as any)
const CrosswordSplatRoute = CrosswordSplatRouteImport.update({
  id: '/crossword/$',
  path: '/crossword/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsListRoute = TagsListRouteImport.update({
  id: '/tags/list',
  path: '/tags/list',
  getParentRoute: () => rootRouteImport,
} as any)
const HubCollectionsSlugRoute = HubCollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => HubRoute,
} as any)
const AnveshiauthAuthRoute = AnveshiauthAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => AnveshiRouteRoute,
} as any)
const AnveshipublicPublicRoute = AnveshipublicPublicRouteImport.update({
  id: '/(public)/_public',
  getParentRoute: () => AnveshiRouteRoute,
} as any)
const ApiQstashNew_puzzle_notificationRoute =
  ApiQstashNew_puzzle_notificationRouteImport.update({
    id: '/api/qstash/new_puzzle_notification',
    path: '/api/qstash/new_puzzle_notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQstashSave_ai_batch_resultsRoute =
  ApiQstashSave_ai_batch_resultsRouteImport.update({
    id: '/api/qstash/save_ai_batch_results',
    path: '/api/qstash/save_ai_batch_results',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQstashSchedule_listingRoute =
  ApiQstashSchedule_listingRouteImport.update({
    id: '/api/qstash/schedule_listing',
    path: '/api/qstash/schedule_listing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BhramitAauthAuthRoute = BhramitAauthAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => BhramitARouteRoute,
} as any)
const BhramitApublicPublicRoute = BhramitApublicPublicRouteImport.update({
  id: '/(public)/_public',
  getParentRoute: () => BhramitARouteRoute,
} as any)
const CollectionsEditUidRoute = CollectionsEditUidRouteImport.update({
  id: '/collections/edit/$uid',
  path: '/collections/edit/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const DvayiauthAuthRoute = DvayiauthAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => DvayiRouteRoute,
} as any)
const DvayipublicPublicRoute = DvayipublicPublicRouteImport.update({
  id: '/(public)/_public',
  getParentRoute: () => DvayiRouteRoute,
} as any)
const PadajalaauthAuthRoute = PadajalaauthAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => PadajalaRouteRoute,
} as any)
const PadajalapublicPublicRoute = PadajalapublicPublicRouteImport.update({
  id: '/(public)/_public',
  getParentRoute: () => PadajalaRouteRoute,
} as any)
const PadavaliauthAuthRoute = PadavaliauthAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => PadavaliRouteRoute,
} as any)
const PadavalipublicPublicRoute = PadavalipublicPublicRouteImport.update({
  id: '/(public)/_public',
  getParentRoute: () => PadavaliRouteRoute,
} as any)
const SurUpaauthAuthRoute = SurUpaauthAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => SurUpaRouteRoute,
} as any)
const SurUpapublicPublicRoute = SurUpapublicPublicRouteImport.update({
  id: '/(public)/_public',
  getParentRoute: () => SurUpaRouteRoute,
} as any)
const TagsEditSlugRoute = TagsEditSlugRouteImport.update({
  id: '/tags/edit/$slug',
  path: '/tags/edit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnveshipublicPublicIndexRoute =
  AnveshipublicPublicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AnveshipublicPublicRoute,
  } as any)
const AnveshipublicPublicSlugRoute = AnveshipublicPublicSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AnveshipublicPublicRoute,
} as any)
const ApiQstashCrosswordSchedule_listingRoute =
  ApiQstashCrosswordSchedule_listingRouteImport.update({
    id: '/api/qstash/crossword/schedule_listing',
    path: '/api/qstash/crossword/schedule_listing',
    getParentRoute: () => rootRouteImport,
  } as any)
const BhramitApublicPublicIndexRoute =
  BhramitApublicPublicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BhramitApublicPublicRoute,
  } as any)
const BhramitApublicPublicSlugRoute =
  BhramitApublicPublicSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => BhramitApublicPublicRoute,
  } as any)
const DvayipublicPublicIndexRoute = DvayipublicPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DvayipublicPublicRoute,
} as any)
const DvayipublicPublicSlugRoute = DvayipublicPublicSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DvayipublicPublicRoute,
} as any)
const PadajalapublicPublicIndexRoute =
  PadajalapublicPublicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PadajalapublicPublicRoute,
  } as any)
const PadajalapublicPublicSlugRoute =
  PadajalapublicPublicSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => PadajalapublicPublicRoute,
  } as any)
const PadavalipublicPublicIndexRoute =
  PadavalipublicPublicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PadavalipublicPublicRoute,
  } as any)
const PadavalipublicPublicSlugRoute =
  PadavalipublicPublicSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => PadavalipublicPublicRoute,
  } as any)
const SurUpapublicPublicIndexRoute = SurUpapublicPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SurUpapublicPublicRoute,
} as any)
const SurUpapublicPublicSlugRoute = SurUpapublicPublicSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SurUpapublicPublicRoute,
} as any)
const AnveshiauthAuthAnalyticsIndexRoute =
  AnveshiauthAuthAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AnveshiauthAuthRoute,
  } as any)
const AnveshiauthAuthEditIdRoute = AnveshiauthAuthEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AnveshiauthAuthRoute,
} as any)
const AnveshiauthAuthListIndexRoute =
  AnveshiauthAuthListIndexRouteImport.update({
    id: '/list/',
    path: '/list/',
    getParentRoute: () => AnveshiauthAuthRoute,
  } as any)
const AnveshipublicPublicPuzzlesIndexRoute =
  AnveshipublicPublicPuzzlesIndexRouteImport.update({
    id: '/puzzles/',
    path: '/puzzles/',
    getParentRoute: () => AnveshipublicPublicRoute,
  } as any)
const AnveshipublicPublicViewNano_idRoute =
  AnveshipublicPublicViewNano_idRouteImport.update({
    id: '/view/$nano_id',
    path: '/view/$nano_id',
    getParentRoute: () => AnveshipublicPublicRoute,
  } as any)
const BhramitAauthAuthAnalyticsIndexRoute =
  BhramitAauthAuthAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => BhramitAauthAuthRoute,
  } as any)
const BhramitAauthAuthEditIdRoute = BhramitAauthAuthEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => BhramitAauthAuthRoute,
} as any)
const BhramitAauthAuthListIndexRoute =
  BhramitAauthAuthListIndexRouteImport.update({
    id: '/list/',
    path: '/list/',
    getParentRoute: () => BhramitAauthAuthRoute,
  } as any)
const BhramitApublicPublicPuzzlesIndexRoute =
  BhramitApublicPublicPuzzlesIndexRouteImport.update({
    id: '/puzzles/',
    path: '/puzzles/',
    getParentRoute: () => BhramitApublicPublicRoute,
  } as any)
const BhramitApublicPublicViewNano_idRoute =
  BhramitApublicPublicViewNano_idRouteImport.update({
    id: '/view/$nano_id',
    path: '/view/$nano_id',
    getParentRoute: () => BhramitApublicPublicRoute,
  } as any)
const DvayiauthAuthAnalyticsIndexRoute =
  DvayiauthAuthAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => DvayiauthAuthRoute,
  } as any)
const DvayiauthAuthEditIdRoute = DvayiauthAuthEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => DvayiauthAuthRoute,
} as any)
const DvayiauthAuthListIndexRoute = DvayiauthAuthListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => DvayiauthAuthRoute,
} as any)
const DvayipublicPublicPuzzlesIndexRoute =
  DvayipublicPublicPuzzlesIndexRouteImport.update({
    id: '/puzzles/',
    path: '/puzzles/',
    getParentRoute: () => DvayipublicPublicRoute,
  } as any)
const DvayipublicPublicViewNano_idRoute =
  DvayipublicPublicViewNano_idRouteImport.update({
    id: '/view/$nano_id',
    path: '/view/$nano_id',
    getParentRoute: () => DvayipublicPublicRoute,
  } as any)
const PadajalaauthAuthAnalyticsIndexRoute =
  PadajalaauthAuthAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => PadajalaauthAuthRoute,
  } as any)
const PadajalaauthAuthBatch_managerIndexRoute =
  PadajalaauthAuthBatch_managerIndexRouteImport.update({
    id: '/batch_manager/',
    path: '/batch_manager/',
    getParentRoute: () => PadajalaauthAuthRoute,
  } as any)
const PadajalaauthAuthCollectionsUidRoute =
  PadajalaauthAuthCollectionsUidRouteImport.update({
    id: '/collections/$uid',
    path: '/collections/$uid',
    getParentRoute: () => PadajalaauthAuthRoute,
  } as any)
const PadajalaauthAuthEditIdRoute = PadajalaauthAuthEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => PadajalaauthAuthRoute,
} as any)
const PadajalaauthAuthListIndexRoute =
  PadajalaauthAuthListIndexRouteImport.update({
    id: '/list/',
    path: '/list/',
    getParentRoute: () => PadajalaauthAuthRoute,
  } as any)
const PadajalaauthAuthSchedulesIndexRoute =
  PadajalaauthAuthSchedulesIndexRouteImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => PadajalaauthAuthRoute,
  } as any)
const PadajalapublicPublicArchivedId_uuidRoute =
  PadajalapublicPublicArchivedId_uuidRouteImport.update({
    id: '/archived/$id_uuid',
    path: '/archived/$id_uuid',
    getParentRoute: () => PadajalapublicPublicRoute,
  } as any)
const PadajalapublicPublicPuzzleSlugRoute =
  PadajalapublicPublicPuzzleSlugRouteImport.update({
    id: '/puzzle/$slug',
    path: '/puzzle/$slug',
    getParentRoute: () => PadajalapublicPublicRoute,
  } as any)
const PadajalapublicPublicPuzzlesIndexRoute =
  PadajalapublicPublicPuzzlesIndexRouteImport.update({
    id: '/puzzles/',
    path: '/puzzles/',
    getParentRoute: () => PadajalapublicPublicRoute,
  } as any)
const PadajalapublicPublicViewNano_idRoute =
  PadajalapublicPublicViewNano_idRouteImport.update({
    id: '/view/$nano_id',
    path: '/view/$nano_id',
    getParentRoute: () => PadajalapublicPublicRoute,
  } as any)
const PadavaliauthAuthAnalyticsIndexRoute =
  PadavaliauthAuthAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => PadavaliauthAuthRoute,
  } as any)
const PadavaliauthAuthBatch_managerIndexRoute =
  PadavaliauthAuthBatch_managerIndexRouteImport.update({
    id: '/batch_manager/',
    path: '/batch_manager/',
    getParentRoute: () => PadavaliauthAuthRoute,
  } as any)
const PadavaliauthAuthCollectionsUidRoute =
  PadavaliauthAuthCollectionsUidRouteImport.update({
    id: '/collections/$uid',
    path: '/collections/$uid',
    getParentRoute: () => PadavaliauthAuthRoute,
  } as any)
const PadavaliauthAuthEditIdRoute = PadavaliauthAuthEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => PadavaliauthAuthRoute,
} as any)
const PadavaliauthAuthListIndexRoute =
  PadavaliauthAuthListIndexRouteImport.update({
    id: '/list/',
    path: '/list/',
    getParentRoute: () => PadavaliauthAuthRoute,
  } as any)
const PadavaliauthAuthSchedulesIndexRoute =
  PadavaliauthAuthSchedulesIndexRouteImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => PadavaliauthAuthRoute,
  } as any)
const PadavalipublicPublicArchivedId_uuidRoute =
  PadavalipublicPublicArchivedId_uuidRouteImport.update({
    id: '/archived/$id_uuid',
    path: '/archived/$id_uuid',
    getParentRoute: () => PadavalipublicPublicRoute,
  } as any)
const PadavalipublicPublicPuzzleSlugRoute =
  PadavalipublicPublicPuzzleSlugRouteImport.update({
    id: '/puzzle/$slug',
    path: '/puzzle/$slug',
    getParentRoute: () => PadavalipublicPublicRoute,
  } as any)
const PadavalipublicPublicPuzzlesIndexRoute =
  PadavalipublicPublicPuzzlesIndexRouteImport.update({
    id: '/puzzles/',
    path: '/puzzles/',
    getParentRoute: () => PadavalipublicPublicRoute,
  } as any)
const PadavalipublicPublicViewNano_idRoute =
  PadavalipublicPublicViewNano_idRouteImport.update({
    id: '/view/$nano_id',
    path: '/view/$nano_id',
    getParentRoute: () => PadavalipublicPublicRoute,
  } as any)
const SurUpaauthAuthAnalyticsIndexRoute =
  SurUpaauthAuthAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => SurUpaauthAuthRoute,
  } as any)
const SurUpaauthAuthEditIdRoute = SurUpaauthAuthEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => SurUpaauthAuthRoute,
} as any)
const SurUpaauthAuthListIndexRoute = SurUpaauthAuthListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => SurUpaauthAuthRoute,
} as any)
const SurUpapublicPublicPuzzlesIndexRoute =
  SurUpapublicPublicPuzzlesIndexRouteImport.update({
    id: '/puzzles/',
    path: '/puzzles/',
    getParentRoute: () => SurUpapublicPublicRoute,
  } as any)
const SurUpapublicPublicViewNano_idRoute =
  SurUpapublicPublicViewNano_idRouteImport.update({
    id: '/view/$nano_id',
    path: '/view/$nano_id',
    getParentRoute: () => SurUpapublicPublicRoute,
  } as any)
const PadajalaauthAuthSchedulesAddIndexRoute =
  PadajalaauthAuthSchedulesAddIndexRouteImport.update({
    id: '/schedules/add/',
    path: '/schedules/add/',
    getParentRoute: () => PadajalaauthAuthRoute,
  } as any)
const PadajalaauthAuthSchedulesEditIdRoute =
  PadajalaauthAuthSchedulesEditIdRouteImport.update({
    id: '/schedules/edit/$id',
    path: '/schedules/edit/$id',
    getParentRoute: () => PadajalaauthAuthRoute,
  } as any)
const PadavaliauthAuthSchedulesAddIndexRoute =
  PadavaliauthAuthSchedulesAddIndexRouteImport.update({
    id: '/schedules/add/',
    path: '/schedules/add/',
    getParentRoute: () => PadavaliauthAuthRoute,
  } as any)
const PadavaliauthAuthSchedulesEditIdRoute =
  PadavaliauthAuthSchedulesEditIdRouteImport.update({
    id: '/schedules/edit/$id',
    path: '/schedules/edit/$id',
    getParentRoute: () => PadavaliauthAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/anveshi': typeof AnveshiRouteRouteWithChildren
  '/bhramitA': typeof BhramitARouteRouteWithChildren
  '/dvayi': typeof DvayiRouteRouteWithChildren
  '/padajala': typeof PadajalaRouteRouteWithChildren
  '/padavali': typeof PadavaliRouteRouteWithChildren
  '/surUpa': typeof SurUpaRouteRouteWithChildren
  '/': typeof HubIndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-0.xml': typeof Sitemap0DotxmlRoute
  '/sitemap-1.xml': typeof Sitemap1DotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/puzzles': typeof HubPuzzlesRoute
  '/collections/list': typeof CollectionsListRoute
  '/crossword/$': typeof CrosswordSplatRoute
  '/tags/list': typeof TagsListRoute
  '/collections/$slug': typeof HubCollectionsSlugRoute
  '/api/qstash/new_puzzle_notification': typeof ApiQstashNew_puzzle_notificationRoute
  '/api/qstash/save_ai_batch_results': typeof ApiQstashSave_ai_batch_resultsRoute
  '/api/qstash/schedule_listing': typeof ApiQstashSchedule_listingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/collections/edit/$uid': typeof CollectionsEditUidRoute
  '/tags/edit/$slug': typeof TagsEditSlugRoute
  '/anveshi/$slug': typeof AnveshipublicPublicSlugRoute
  '/api/qstash/crossword/schedule_listing': typeof ApiQstashCrosswordSchedule_listingRoute
  '/bhramitA/$slug': typeof BhramitApublicPublicSlugRoute
  '/dvayi/$slug': typeof DvayipublicPublicSlugRoute
  '/padajala/$slug': typeof PadajalapublicPublicSlugRoute
  '/padavali/$slug': typeof PadavalipublicPublicSlugRoute
  '/surUpa/$slug': typeof SurUpapublicPublicSlugRoute
  '/anveshi/': typeof AnveshipublicPublicIndexRoute
  '/bhramitA/': typeof BhramitApublicPublicIndexRoute
  '/dvayi/': typeof DvayipublicPublicIndexRoute
  '/padajala/': typeof PadajalapublicPublicIndexRoute
  '/padavali/': typeof PadavalipublicPublicIndexRoute
  '/surUpa/': typeof SurUpapublicPublicIndexRoute
  '/anveshi/edit/$id': typeof AnveshiauthAuthEditIdRoute
  '/anveshi/view/$nano_id': typeof AnveshipublicPublicViewNano_idRoute
  '/bhramitA/edit/$id': typeof BhramitAauthAuthEditIdRoute
  '/bhramitA/view/$nano_id': typeof BhramitApublicPublicViewNano_idRoute
  '/dvayi/edit/$id': typeof DvayiauthAuthEditIdRoute
  '/dvayi/view/$nano_id': typeof DvayipublicPublicViewNano_idRoute
  '/padajala/collections/$uid': typeof PadajalaauthAuthCollectionsUidRoute
  '/padajala/edit/$id': typeof PadajalaauthAuthEditIdRoute
  '/padajala/archived/$id_uuid': typeof PadajalapublicPublicArchivedId_uuidRoute
  '/padajala/puzzle/$slug': typeof PadajalapublicPublicPuzzleSlugRoute
  '/padajala/view/$nano_id': typeof PadajalapublicPublicViewNano_idRoute
  '/padavali/collections/$uid': typeof PadavaliauthAuthCollectionsUidRoute
  '/padavali/edit/$id': typeof PadavaliauthAuthEditIdRoute
  '/padavali/archived/$id_uuid': typeof PadavalipublicPublicArchivedId_uuidRoute
  '/padavali/puzzle/$slug': typeof PadavalipublicPublicPuzzleSlugRoute
  '/padavali/view/$nano_id': typeof PadavalipublicPublicViewNano_idRoute
  '/surUpa/edit/$id': typeof SurUpaauthAuthEditIdRoute
  '/surUpa/view/$nano_id': typeof SurUpapublicPublicViewNano_idRoute
  '/anveshi/analytics/': typeof AnveshiauthAuthAnalyticsIndexRoute
  '/anveshi/list/': typeof AnveshiauthAuthListIndexRoute
  '/anveshi/puzzles/': typeof AnveshipublicPublicPuzzlesIndexRoute
  '/bhramitA/analytics/': typeof BhramitAauthAuthAnalyticsIndexRoute
  '/bhramitA/list/': typeof BhramitAauthAuthListIndexRoute
  '/bhramitA/puzzles/': typeof BhramitApublicPublicPuzzlesIndexRoute
  '/dvayi/analytics/': typeof DvayiauthAuthAnalyticsIndexRoute
  '/dvayi/list/': typeof DvayiauthAuthListIndexRoute
  '/dvayi/puzzles/': typeof DvayipublicPublicPuzzlesIndexRoute
  '/padajala/analytics/': typeof PadajalaauthAuthAnalyticsIndexRoute
  '/padajala/batch_manager/': typeof PadajalaauthAuthBatch_managerIndexRoute
  '/padajala/list/': typeof PadajalaauthAuthListIndexRoute
  '/padajala/schedules/': typeof PadajalaauthAuthSchedulesIndexRoute
  '/padajala/puzzles/': typeof PadajalapublicPublicPuzzlesIndexRoute
  '/padavali/analytics/': typeof PadavaliauthAuthAnalyticsIndexRoute
  '/padavali/batch_manager/': typeof PadavaliauthAuthBatch_managerIndexRoute
  '/padavali/list/': typeof PadavaliauthAuthListIndexRoute
  '/padavali/schedules/': typeof PadavaliauthAuthSchedulesIndexRoute
  '/padavali/puzzles/': typeof PadavalipublicPublicPuzzlesIndexRoute
  '/surUpa/analytics/': typeof SurUpaauthAuthAnalyticsIndexRoute
  '/surUpa/list/': typeof SurUpaauthAuthListIndexRoute
  '/surUpa/puzzles/': typeof SurUpapublicPublicPuzzlesIndexRoute
  '/padajala/schedules/edit/$id': typeof PadajalaauthAuthSchedulesEditIdRoute
  '/padavali/schedules/edit/$id': typeof PadavaliauthAuthSchedulesEditIdRoute
  '/padajala/schedules/add/': typeof PadajalaauthAuthSchedulesAddIndexRoute
  '/padavali/schedules/add/': typeof PadavaliauthAuthSchedulesAddIndexRoute
}
export interface FileRoutesByTo {
  '/anveshi': typeof AnveshipublicPublicIndexRoute
  '/bhramitA': typeof BhramitApublicPublicIndexRoute
  '/dvayi': typeof DvayipublicPublicIndexRoute
  '/padajala': typeof PadajalapublicPublicIndexRoute
  '/padavali': typeof PadavalipublicPublicIndexRoute
  '/surUpa': typeof SurUpapublicPublicIndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-0.xml': typeof Sitemap0DotxmlRoute
  '/sitemap-1.xml': typeof Sitemap1DotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/puzzles': typeof HubPuzzlesRoute
  '/collections/list': typeof CollectionsListRoute
  '/crossword/$': typeof CrosswordSplatRoute
  '/tags/list': typeof TagsListRoute
  '/': typeof HubIndexRoute
  '/collections/$slug': typeof HubCollectionsSlugRoute
  '/api/qstash/new_puzzle_notification': typeof ApiQstashNew_puzzle_notificationRoute
  '/api/qstash/save_ai_batch_results': typeof ApiQstashSave_ai_batch_resultsRoute
  '/api/qstash/schedule_listing': typeof ApiQstashSchedule_listingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/collections/edit/$uid': typeof CollectionsEditUidRoute
  '/tags/edit/$slug': typeof TagsEditSlugRoute
  '/anveshi/$slug': typeof AnveshipublicPublicSlugRoute
  '/api/qstash/crossword/schedule_listing': typeof ApiQstashCrosswordSchedule_listingRoute
  '/bhramitA/$slug': typeof BhramitApublicPublicSlugRoute
  '/dvayi/$slug': typeof DvayipublicPublicSlugRoute
  '/padajala/$slug': typeof PadajalapublicPublicSlugRoute
  '/padavali/$slug': typeof PadavalipublicPublicSlugRoute
  '/surUpa/$slug': typeof SurUpapublicPublicSlugRoute
  '/anveshi/edit/$id': typeof AnveshiauthAuthEditIdRoute
  '/anveshi/view/$nano_id': typeof AnveshipublicPublicViewNano_idRoute
  '/bhramitA/edit/$id': typeof BhramitAauthAuthEditIdRoute
  '/bhramitA/view/$nano_id': typeof BhramitApublicPublicViewNano_idRoute
  '/dvayi/edit/$id': typeof DvayiauthAuthEditIdRoute
  '/dvayi/view/$nano_id': typeof DvayipublicPublicViewNano_idRoute
  '/padajala/collections/$uid': typeof PadajalaauthAuthCollectionsUidRoute
  '/padajala/edit/$id': typeof PadajalaauthAuthEditIdRoute
  '/padajala/archived/$id_uuid': typeof PadajalapublicPublicArchivedId_uuidRoute
  '/padajala/puzzle/$slug': typeof PadajalapublicPublicPuzzleSlugRoute
  '/padajala/view/$nano_id': typeof PadajalapublicPublicViewNano_idRoute
  '/padavali/collections/$uid': typeof PadavaliauthAuthCollectionsUidRoute
  '/padavali/edit/$id': typeof PadavaliauthAuthEditIdRoute
  '/padavali/archived/$id_uuid': typeof PadavalipublicPublicArchivedId_uuidRoute
  '/padavali/puzzle/$slug': typeof PadavalipublicPublicPuzzleSlugRoute
  '/padavali/view/$nano_id': typeof PadavalipublicPublicViewNano_idRoute
  '/surUpa/edit/$id': typeof SurUpaauthAuthEditIdRoute
  '/surUpa/view/$nano_id': typeof SurUpapublicPublicViewNano_idRoute
  '/anveshi/analytics': typeof AnveshiauthAuthAnalyticsIndexRoute
  '/anveshi/list': typeof AnveshiauthAuthListIndexRoute
  '/anveshi/puzzles': typeof AnveshipublicPublicPuzzlesIndexRoute
  '/bhramitA/analytics': typeof BhramitAauthAuthAnalyticsIndexRoute
  '/bhramitA/list': typeof BhramitAauthAuthListIndexRoute
  '/bhramitA/puzzles': typeof BhramitApublicPublicPuzzlesIndexRoute
  '/dvayi/analytics': typeof DvayiauthAuthAnalyticsIndexRoute
  '/dvayi/list': typeof DvayiauthAuthListIndexRoute
  '/dvayi/puzzles': typeof DvayipublicPublicPuzzlesIndexRoute
  '/padajala/analytics': typeof PadajalaauthAuthAnalyticsIndexRoute
  '/padajala/batch_manager': typeof PadajalaauthAuthBatch_managerIndexRoute
  '/padajala/list': typeof PadajalaauthAuthListIndexRoute
  '/padajala/schedules': typeof PadajalaauthAuthSchedulesIndexRoute
  '/padajala/puzzles': typeof PadajalapublicPublicPuzzlesIndexRoute
  '/padavali/analytics': typeof PadavaliauthAuthAnalyticsIndexRoute
  '/padavali/batch_manager': typeof PadavaliauthAuthBatch_managerIndexRoute
  '/padavali/list': typeof PadavaliauthAuthListIndexRoute
  '/padavali/schedules': typeof PadavaliauthAuthSchedulesIndexRoute
  '/padavali/puzzles': typeof PadavalipublicPublicPuzzlesIndexRoute
  '/surUpa/analytics': typeof SurUpaauthAuthAnalyticsIndexRoute
  '/surUpa/list': typeof SurUpaauthAuthListIndexRoute
  '/surUpa/puzzles': typeof SurUpapublicPublicPuzzlesIndexRoute
  '/padajala/schedules/edit/$id': typeof PadajalaauthAuthSchedulesEditIdRoute
  '/padavali/schedules/edit/$id': typeof PadavaliauthAuthSchedulesEditIdRoute
  '/padajala/schedules/add': typeof PadajalaauthAuthSchedulesAddIndexRoute
  '/padavali/schedules/add': typeof PadavaliauthAuthSchedulesAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/anveshi': typeof AnveshiRouteRouteWithChildren
  '/bhramitA': typeof BhramitARouteRouteWithChildren
  '/dvayi': typeof DvayiRouteRouteWithChildren
  '/padajala': typeof PadajalaRouteRouteWithChildren
  '/padavali': typeof PadavaliRouteRouteWithChildren
  '/surUpa': typeof SurUpaRouteRouteWithChildren
  '/_hub': typeof HubRouteWithChildren
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-0.xml': typeof Sitemap0DotxmlRoute
  '/sitemap-1.xml': typeof Sitemap1DotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/_hub/puzzles': typeof HubPuzzlesRoute
  '/collections/list': typeof CollectionsListRoute
  '/crossword/$': typeof CrosswordSplatRoute
  '/tags/list': typeof TagsListRoute
  '/_hub/': typeof HubIndexRoute
  '/_hub/collections/$slug': typeof HubCollectionsSlugRoute
  '/anveshi/(auth)/_auth': typeof AnveshiauthAuthRouteWithChildren
  '/anveshi/(public)/_public': typeof AnveshipublicPublicRouteWithChildren
  '/api/qstash/new_puzzle_notification': typeof ApiQstashNew_puzzle_notificationRoute
  '/api/qstash/save_ai_batch_results': typeof ApiQstashSave_ai_batch_resultsRoute
  '/api/qstash/schedule_listing': typeof ApiQstashSchedule_listingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/bhramitA/(auth)/_auth': typeof BhramitAauthAuthRouteWithChildren
  '/bhramitA/(public)/_public': typeof BhramitApublicPublicRouteWithChildren
  '/collections/edit/$uid': typeof CollectionsEditUidRoute
  '/dvayi/(auth)/_auth': typeof DvayiauthAuthRouteWithChildren
  '/dvayi/(public)/_public': typeof DvayipublicPublicRouteWithChildren
  '/padajala/(auth)/_auth': typeof PadajalaauthAuthRouteWithChildren
  '/padajala/(public)/_public': typeof PadajalapublicPublicRouteWithChildren
  '/padavali/(auth)/_auth': typeof PadavaliauthAuthRouteWithChildren
  '/padavali/(public)/_public': typeof PadavalipublicPublicRouteWithChildren
  '/surUpa/(auth)/_auth': typeof SurUpaauthAuthRouteWithChildren
  '/surUpa/(public)/_public': typeof SurUpapublicPublicRouteWithChildren
  '/tags/edit/$slug': typeof TagsEditSlugRoute
  '/anveshi/(public)/_public/$slug': typeof AnveshipublicPublicSlugRoute
  '/api/qstash/crossword/schedule_listing': typeof ApiQstashCrosswordSchedule_listingRoute
  '/bhramitA/(public)/_public/$slug': typeof BhramitApublicPublicSlugRoute
  '/dvayi/(public)/_public/$slug': typeof DvayipublicPublicSlugRoute
  '/padajala/(public)/_public/$slug': typeof PadajalapublicPublicSlugRoute
  '/padavali/(public)/_public/$slug': typeof PadavalipublicPublicSlugRoute
  '/surUpa/(public)/_public/$slug': typeof SurUpapublicPublicSlugRoute
  '/anveshi/(public)/_public/': typeof AnveshipublicPublicIndexRoute
  '/bhramitA/(public)/_public/': typeof BhramitApublicPublicIndexRoute
  '/dvayi/(public)/_public/': typeof DvayipublicPublicIndexRoute
  '/padajala/(public)/_public/': typeof PadajalapublicPublicIndexRoute
  '/padavali/(public)/_public/': typeof PadavalipublicPublicIndexRoute
  '/surUpa/(public)/_public/': typeof SurUpapublicPublicIndexRoute
  '/anveshi/(auth)/_auth/edit/$id': typeof AnveshiauthAuthEditIdRoute
  '/anveshi/(public)/_public/view/$nano_id': typeof AnveshipublicPublicViewNano_idRoute
  '/bhramitA/(auth)/_auth/edit/$id': typeof BhramitAauthAuthEditIdRoute
  '/bhramitA/(public)/_public/view/$nano_id': typeof BhramitApublicPublicViewNano_idRoute
  '/dvayi/(auth)/_auth/edit/$id': typeof DvayiauthAuthEditIdRoute
  '/dvayi/(public)/_public/view/$nano_id': typeof DvayipublicPublicViewNano_idRoute
  '/padajala/(auth)/_auth/collections/$uid': typeof PadajalaauthAuthCollectionsUidRoute
  '/padajala/(auth)/_auth/edit/$id': typeof PadajalaauthAuthEditIdRoute
  '/padajala/(public)/_public/archived/$id_uuid': typeof PadajalapublicPublicArchivedId_uuidRoute
  '/padajala/(public)/_public/puzzle/$slug': typeof PadajalapublicPublicPuzzleSlugRoute
  '/padajala/(public)/_public/view/$nano_id': typeof PadajalapublicPublicViewNano_idRoute
  '/padavali/(auth)/_auth/collections/$uid': typeof PadavaliauthAuthCollectionsUidRoute
  '/padavali/(auth)/_auth/edit/$id': typeof PadavaliauthAuthEditIdRoute
  '/padavali/(public)/_public/archived/$id_uuid': typeof PadavalipublicPublicArchivedId_uuidRoute
  '/padavali/(public)/_public/puzzle/$slug': typeof PadavalipublicPublicPuzzleSlugRoute
  '/padavali/(public)/_public/view/$nano_id': typeof PadavalipublicPublicViewNano_idRoute
  '/surUpa/(auth)/_auth/edit/$id': typeof SurUpaauthAuthEditIdRoute
  '/surUpa/(public)/_public/view/$nano_id': typeof SurUpapublicPublicViewNano_idRoute
  '/anveshi/(auth)/_auth/analytics/': typeof AnveshiauthAuthAnalyticsIndexRoute
  '/anveshi/(auth)/_auth/list/': typeof AnveshiauthAuthListIndexRoute
  '/anveshi/(public)/_public/puzzles/': typeof AnveshipublicPublicPuzzlesIndexRoute
  '/bhramitA/(auth)/_auth/analytics/': typeof BhramitAauthAuthAnalyticsIndexRoute
  '/bhramitA/(auth)/_auth/list/': typeof BhramitAauthAuthListIndexRoute
  '/bhramitA/(public)/_public/puzzles/': typeof BhramitApublicPublicPuzzlesIndexRoute
  '/dvayi/(auth)/_auth/analytics/': typeof DvayiauthAuthAnalyticsIndexRoute
  '/dvayi/(auth)/_auth/list/': typeof DvayiauthAuthListIndexRoute
  '/dvayi/(public)/_public/puzzles/': typeof DvayipublicPublicPuzzlesIndexRoute
  '/padajala/(auth)/_auth/analytics/': typeof PadajalaauthAuthAnalyticsIndexRoute
  '/padajala/(auth)/_auth/batch_manager/': typeof PadajalaauthAuthBatch_managerIndexRoute
  '/padajala/(auth)/_auth/list/': typeof PadajalaauthAuthListIndexRoute
  '/padajala/(auth)/_auth/schedules/': typeof PadajalaauthAuthSchedulesIndexRoute
  '/padajala/(public)/_public/puzzles/': typeof PadajalapublicPublicPuzzlesIndexRoute
  '/padavali/(auth)/_auth/analytics/': typeof PadavaliauthAuthAnalyticsIndexRoute
  '/padavali/(auth)/_auth/batch_manager/': typeof PadavaliauthAuthBatch_managerIndexRoute
  '/padavali/(auth)/_auth/list/': typeof PadavaliauthAuthListIndexRoute
  '/padavali/(auth)/_auth/schedules/': typeof PadavaliauthAuthSchedulesIndexRoute
  '/padavali/(public)/_public/puzzles/': typeof PadavalipublicPublicPuzzlesIndexRoute
  '/surUpa/(auth)/_auth/analytics/': typeof SurUpaauthAuthAnalyticsIndexRoute
  '/surUpa/(auth)/_auth/list/': typeof SurUpaauthAuthListIndexRoute
  '/surUpa/(public)/_public/puzzles/': typeof SurUpapublicPublicPuzzlesIndexRoute
  '/padajala/(auth)/_auth/schedules/edit/$id': typeof PadajalaauthAuthSchedulesEditIdRoute
  '/padavali/(auth)/_auth/schedules/edit/$id': typeof PadavaliauthAuthSchedulesEditIdRoute
  '/padajala/(auth)/_auth/schedules/add/': typeof PadajalaauthAuthSchedulesAddIndexRoute
  '/padavali/(auth)/_auth/schedules/add/': typeof PadavaliauthAuthSchedulesAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/anveshi'
    | '/bhramitA'
    | '/dvayi'
    | '/padajala'
    | '/padavali'
    | '/surUpa'
    | '/'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/explore'
    | '/robots.txt'
    | '/sitemap-0.xml'
    | '/sitemap-1.xml'
    | '/sitemap-index.xml'
    | '/puzzles'
    | '/collections/list'
    | '/crossword/$'
    | '/tags/list'
    | '/collections/$slug'
    | '/api/qstash/new_puzzle_notification'
    | '/api/qstash/save_ai_batch_results'
    | '/api/qstash/schedule_listing'
    | '/api/trpc/$'
    | '/collections/edit/$uid'
    | '/tags/edit/$slug'
    | '/anveshi/$slug'
    | '/api/qstash/crossword/schedule_listing'
    | '/bhramitA/$slug'
    | '/dvayi/$slug'
    | '/padajala/$slug'
    | '/padavali/$slug'
    | '/surUpa/$slug'
    | '/anveshi/'
    | '/bhramitA/'
    | '/dvayi/'
    | '/padajala/'
    | '/padavali/'
    | '/surUpa/'
    | '/anveshi/edit/$id'
    | '/anveshi/view/$nano_id'
    | '/bhramitA/edit/$id'
    | '/bhramitA/view/$nano_id'
    | '/dvayi/edit/$id'
    | '/dvayi/view/$nano_id'
    | '/padajala/collections/$uid'
    | '/padajala/edit/$id'
    | '/padajala/archived/$id_uuid'
    | '/padajala/puzzle/$slug'
    | '/padajala/view/$nano_id'
    | '/padavali/collections/$uid'
    | '/padavali/edit/$id'
    | '/padavali/archived/$id_uuid'
    | '/padavali/puzzle/$slug'
    | '/padavali/view/$nano_id'
    | '/surUpa/edit/$id'
    | '/surUpa/view/$nano_id'
    | '/anveshi/analytics/'
    | '/anveshi/list/'
    | '/anveshi/puzzles/'
    | '/bhramitA/analytics/'
    | '/bhramitA/list/'
    | '/bhramitA/puzzles/'
    | '/dvayi/analytics/'
    | '/dvayi/list/'
    | '/dvayi/puzzles/'
    | '/padajala/analytics/'
    | '/padajala/batch_manager/'
    | '/padajala/list/'
    | '/padajala/schedules/'
    | '/padajala/puzzles/'
    | '/padavali/analytics/'
    | '/padavali/batch_manager/'
    | '/padavali/list/'
    | '/padavali/schedules/'
    | '/padavali/puzzles/'
    | '/surUpa/analytics/'
    | '/surUpa/list/'
    | '/surUpa/puzzles/'
    | '/padajala/schedules/edit/$id'
    | '/padavali/schedules/edit/$id'
    | '/padajala/schedules/add/'
    | '/padavali/schedules/add/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/anveshi'
    | '/bhramitA'
    | '/dvayi'
    | '/padajala'
    | '/padavali'
    | '/surUpa'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/explore'
    | '/robots.txt'
    | '/sitemap-0.xml'
    | '/sitemap-1.xml'
    | '/sitemap-index.xml'
    | '/puzzles'
    | '/collections/list'
    | '/crossword/$'
    | '/tags/list'
    | '/'
    | '/collections/$slug'
    | '/api/qstash/new_puzzle_notification'
    | '/api/qstash/save_ai_batch_results'
    | '/api/qstash/schedule_listing'
    | '/api/trpc/$'
    | '/collections/edit/$uid'
    | '/tags/edit/$slug'
    | '/anveshi/$slug'
    | '/api/qstash/crossword/schedule_listing'
    | '/bhramitA/$slug'
    | '/dvayi/$slug'
    | '/padajala/$slug'
    | '/padavali/$slug'
    | '/surUpa/$slug'
    | '/anveshi/edit/$id'
    | '/anveshi/view/$nano_id'
    | '/bhramitA/edit/$id'
    | '/bhramitA/view/$nano_id'
    | '/dvayi/edit/$id'
    | '/dvayi/view/$nano_id'
    | '/padajala/collections/$uid'
    | '/padajala/edit/$id'
    | '/padajala/archived/$id_uuid'
    | '/padajala/puzzle/$slug'
    | '/padajala/view/$nano_id'
    | '/padavali/collections/$uid'
    | '/padavali/edit/$id'
    | '/padavali/archived/$id_uuid'
    | '/padavali/puzzle/$slug'
    | '/padavali/view/$nano_id'
    | '/surUpa/edit/$id'
    | '/surUpa/view/$nano_id'
    | '/anveshi/analytics'
    | '/anveshi/list'
    | '/anveshi/puzzles'
    | '/bhramitA/analytics'
    | '/bhramitA/list'
    | '/bhramitA/puzzles'
    | '/dvayi/analytics'
    | '/dvayi/list'
    | '/dvayi/puzzles'
    | '/padajala/analytics'
    | '/padajala/batch_manager'
    | '/padajala/list'
    | '/padajala/schedules'
    | '/padajala/puzzles'
    | '/padavali/analytics'
    | '/padavali/batch_manager'
    | '/padavali/list'
    | '/padavali/schedules'
    | '/padavali/puzzles'
    | '/surUpa/analytics'
    | '/surUpa/list'
    | '/surUpa/puzzles'
    | '/padajala/schedules/edit/$id'
    | '/padavali/schedules/edit/$id'
    | '/padajala/schedules/add'
    | '/padavali/schedules/add'
  id:
    | '__root__'
    | '/anveshi'
    | '/bhramitA'
    | '/dvayi'
    | '/padajala'
    | '/padavali'
    | '/surUpa'
    | '/_hub'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/explore'
    | '/robots.txt'
    | '/sitemap-0.xml'
    | '/sitemap-1.xml'
    | '/sitemap-index.xml'
    | '/_hub/puzzles'
    | '/collections/list'
    | '/crossword/$'
    | '/tags/list'
    | '/_hub/'
    | '/_hub/collections/$slug'
    | '/anveshi/(auth)/_auth'
    | '/anveshi/(public)/_public'
    | '/api/qstash/new_puzzle_notification'
    | '/api/qstash/save_ai_batch_results'
    | '/api/qstash/schedule_listing'
    | '/api/trpc/$'
    | '/bhramitA/(auth)/_auth'
    | '/bhramitA/(public)/_public'
    | '/collections/edit/$uid'
    | '/dvayi/(auth)/_auth'
    | '/dvayi/(public)/_public'
    | '/padajala/(auth)/_auth'
    | '/padajala/(public)/_public'
    | '/padavali/(auth)/_auth'
    | '/padavali/(public)/_public'
    | '/surUpa/(auth)/_auth'
    | '/surUpa/(public)/_public'
    | '/tags/edit/$slug'
    | '/anveshi/(public)/_public/$slug'
    | '/api/qstash/crossword/schedule_listing'
    | '/bhramitA/(public)/_public/$slug'
    | '/dvayi/(public)/_public/$slug'
    | '/padajala/(public)/_public/$slug'
    | '/padavali/(public)/_public/$slug'
    | '/surUpa/(public)/_public/$slug'
    | '/anveshi/(public)/_public/'
    | '/bhramitA/(public)/_public/'
    | '/dvayi/(public)/_public/'
    | '/padajala/(public)/_public/'
    | '/padavali/(public)/_public/'
    | '/surUpa/(public)/_public/'
    | '/anveshi/(auth)/_auth/edit/$id'
    | '/anveshi/(public)/_public/view/$nano_id'
    | '/bhramitA/(auth)/_auth/edit/$id'
    | '/bhramitA/(public)/_public/view/$nano_id'
    | '/dvayi/(auth)/_auth/edit/$id'
    | '/dvayi/(public)/_public/view/$nano_id'
    | '/padajala/(auth)/_auth/collections/$uid'
    | '/padajala/(auth)/_auth/edit/$id'
    | '/padajala/(public)/_public/archived/$id_uuid'
    | '/padajala/(public)/_public/puzzle/$slug'
    | '/padajala/(public)/_public/view/$nano_id'
    | '/padavali/(auth)/_auth/collections/$uid'
    | '/padavali/(auth)/_auth/edit/$id'
    | '/padavali/(public)/_public/archived/$id_uuid'
    | '/padavali/(public)/_public/puzzle/$slug'
    | '/padavali/(public)/_public/view/$nano_id'
    | '/surUpa/(auth)/_auth/edit/$id'
    | '/surUpa/(public)/_public/view/$nano_id'
    | '/anveshi/(auth)/_auth/analytics/'
    | '/anveshi/(auth)/_auth/list/'
    | '/anveshi/(public)/_public/puzzles/'
    | '/bhramitA/(auth)/_auth/analytics/'
    | '/bhramitA/(auth)/_auth/list/'
    | '/bhramitA/(public)/_public/puzzles/'
    | '/dvayi/(auth)/_auth/analytics/'
    | '/dvayi/(auth)/_auth/list/'
    | '/dvayi/(public)/_public/puzzles/'
    | '/padajala/(auth)/_auth/analytics/'
    | '/padajala/(auth)/_auth/batch_manager/'
    | '/padajala/(auth)/_auth/list/'
    | '/padajala/(auth)/_auth/schedules/'
    | '/padajala/(public)/_public/puzzles/'
    | '/padavali/(auth)/_auth/analytics/'
    | '/padavali/(auth)/_auth/batch_manager/'
    | '/padavali/(auth)/_auth/list/'
    | '/padavali/(auth)/_auth/schedules/'
    | '/padavali/(public)/_public/puzzles/'
    | '/surUpa/(auth)/_auth/analytics/'
    | '/surUpa/(auth)/_auth/list/'
    | '/surUpa/(public)/_public/puzzles/'
    | '/padajala/(auth)/_auth/schedules/edit/$id'
    | '/padavali/(auth)/_auth/schedules/edit/$id'
    | '/padajala/(auth)/_auth/schedules/add/'
    | '/padavali/(auth)/_auth/schedules/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AnveshiRouteRoute: typeof AnveshiRouteRouteWithChildren
  BhramitARouteRoute: typeof BhramitARouteRouteWithChildren
  DvayiRouteRoute: typeof DvayiRouteRouteWithChildren
  PadajalaRouteRoute: typeof PadajalaRouteRouteWithChildren
  PadavaliRouteRoute: typeof PadavaliRouteRouteWithChildren
  SurUpaRouteRoute: typeof SurUpaRouteRouteWithChildren
  HubRoute: typeof HubRouteWithChildren
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  Sitemap0DotxmlRoute: typeof Sitemap0DotxmlRoute
  Sitemap1DotxmlRoute: typeof Sitemap1DotxmlRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  CollectionsListRoute: typeof CollectionsListRoute
  CrosswordSplatRoute: typeof CrosswordSplatRoute
  TagsListRoute: typeof TagsListRoute
  ApiQstashNew_puzzle_notificationRoute: typeof ApiQstashNew_puzzle_notificationRoute
  ApiQstashSave_ai_batch_resultsRoute: typeof ApiQstashSave_ai_batch_resultsRoute
  ApiQstashSchedule_listingRoute: typeof ApiQstashSchedule_listingRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  CollectionsEditUidRoute: typeof CollectionsEditUidRoute
  TagsEditSlugRoute: typeof TagsEditSlugRoute
  ApiQstashCrosswordSchedule_listingRoute: typeof ApiQstashCrosswordSchedule_listingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_hub': {
      id: '/_hub'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anveshi': {
      id: '/anveshi'
      path: '/anveshi'
      fullPath: '/anveshi'
      preLoaderRoute: typeof AnveshiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bhramitA': {
      id: '/bhramitA'
      path: '/bhramitA'
      fullPath: '/bhramitA'
      preLoaderRoute: typeof BhramitARouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dvayi': {
      id: '/dvayi'
      path: '/dvayi'
      fullPath: '/dvayi'
      preLoaderRoute: typeof DvayiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/padajala': {
      id: '/padajala'
      path: '/padajala'
      fullPath: '/padajala'
      preLoaderRoute: typeof PadajalaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/padavali': {
      id: '/padavali'
      path: '/padavali'
      fullPath: '/padavali'
      preLoaderRoute: typeof PadavaliRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-0.xml': {
      id: '/sitemap-0.xml'
      path: '/sitemap-0.xml'
      fullPath: '/sitemap-0.xml'
      preLoaderRoute: typeof Sitemap0DotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-1.xml': {
      id: '/sitemap-1.xml'
      path: '/sitemap-1.xml'
      fullPath: '/sitemap-1.xml'
      preLoaderRoute: typeof Sitemap1DotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surUpa': {
      id: '/surUpa'
      path: '/surUpa'
      fullPath: '/surUpa'
      preLoaderRoute: typeof SurUpaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub/': {
      id: '/_hub/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/puzzles': {
      id: '/_hub/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof HubPuzzlesRouteImport
      parentRoute: typeof HubRoute
    }
    '/collections/list': {
      id: '/collections/list'
      path: '/collections/list'
      fullPath: '/collections/list'
      preLoaderRoute: typeof CollectionsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crossword/$': {
      id: '/crossword/$'
      path: '/crossword/$'
      fullPath: '/crossword/$'
      preLoaderRoute: typeof CrosswordSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/list': {
      id: '/tags/list'
      path: '/tags/list'
      fullPath: '/tags/list'
      preLoaderRoute: typeof TagsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub/collections/$slug': {
      id: '/_hub/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof HubCollectionsSlugRouteImport
      parentRoute: typeof HubRoute
    }
    '/anveshi/(auth)/_auth': {
      id: '/anveshi/(auth)/_auth'
      path: ''
      fullPath: '/anveshi'
      preLoaderRoute: typeof AnveshiauthAuthRouteImport
      parentRoute: typeof AnveshiRouteRoute
    }
    '/anveshi/(public)/_public': {
      id: '/anveshi/(public)/_public'
      path: ''
      fullPath: '/anveshi'
      preLoaderRoute: typeof AnveshipublicPublicRouteImport
      parentRoute: typeof AnveshiRouteRoute
    }
    '/api/qstash/new_puzzle_notification': {
      id: '/api/qstash/new_puzzle_notification'
      path: '/api/qstash/new_puzzle_notification'
      fullPath: '/api/qstash/new_puzzle_notification'
      preLoaderRoute: typeof ApiQstashNew_puzzle_notificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qstash/save_ai_batch_results': {
      id: '/api/qstash/save_ai_batch_results'
      path: '/api/qstash/save_ai_batch_results'
      fullPath: '/api/qstash/save_ai_batch_results'
      preLoaderRoute: typeof ApiQstashSave_ai_batch_resultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qstash/schedule_listing': {
      id: '/api/qstash/schedule_listing'
      path: '/api/qstash/schedule_listing'
      fullPath: '/api/qstash/schedule_listing'
      preLoaderRoute: typeof ApiQstashSchedule_listingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bhramitA/(auth)/_auth': {
      id: '/bhramitA/(auth)/_auth'
      path: ''
      fullPath: '/bhramitA'
      preLoaderRoute: typeof BhramitAauthAuthRouteImport
      parentRoute: typeof BhramitARouteRoute
    }
    '/bhramitA/(public)/_public': {
      id: '/bhramitA/(public)/_public'
      path: ''
      fullPath: '/bhramitA'
      preLoaderRoute: typeof BhramitApublicPublicRouteImport
      parentRoute: typeof BhramitARouteRoute
    }
    '/collections/edit/$uid': {
      id: '/collections/edit/$uid'
      path: '/collections/edit/$uid'
      fullPath: '/collections/edit/$uid'
      preLoaderRoute: typeof CollectionsEditUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dvayi/(auth)/_auth': {
      id: '/dvayi/(auth)/_auth'
      path: ''
      fullPath: '/dvayi'
      preLoaderRoute: typeof DvayiauthAuthRouteImport
      parentRoute: typeof DvayiRouteRoute
    }
    '/dvayi/(public)/_public': {
      id: '/dvayi/(public)/_public'
      path: ''
      fullPath: '/dvayi'
      preLoaderRoute: typeof DvayipublicPublicRouteImport
      parentRoute: typeof DvayiRouteRoute
    }
    '/padajala/(auth)/_auth': {
      id: '/padajala/(auth)/_auth'
      path: ''
      fullPath: '/padajala'
      preLoaderRoute: typeof PadajalaauthAuthRouteImport
      parentRoute: typeof PadajalaRouteRoute
    }
    '/padajala/(public)/_public': {
      id: '/padajala/(public)/_public'
      path: ''
      fullPath: '/padajala'
      preLoaderRoute: typeof PadajalapublicPublicRouteImport
      parentRoute: typeof PadajalaRouteRoute
    }
    '/padavali/(auth)/_auth': {
      id: '/padavali/(auth)/_auth'
      path: ''
      fullPath: '/padavali'
      preLoaderRoute: typeof PadavaliauthAuthRouteImport
      parentRoute: typeof PadavaliRouteRoute
    }
    '/padavali/(public)/_public': {
      id: '/padavali/(public)/_public'
      path: ''
      fullPath: '/padavali'
      preLoaderRoute: typeof PadavalipublicPublicRouteImport
      parentRoute: typeof PadavaliRouteRoute
    }
    '/surUpa/(auth)/_auth': {
      id: '/surUpa/(auth)/_auth'
      path: ''
      fullPath: '/surUpa'
      preLoaderRoute: typeof SurUpaauthAuthRouteImport
      parentRoute: typeof SurUpaRouteRoute
    }
    '/surUpa/(public)/_public': {
      id: '/surUpa/(public)/_public'
      path: ''
      fullPath: '/surUpa'
      preLoaderRoute: typeof SurUpapublicPublicRouteImport
      parentRoute: typeof SurUpaRouteRoute
    }
    '/tags/edit/$slug': {
      id: '/tags/edit/$slug'
      path: '/tags/edit/$slug'
      fullPath: '/tags/edit/$slug'
      preLoaderRoute: typeof TagsEditSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anveshi/(public)/_public/': {
      id: '/anveshi/(public)/_public/'
      path: '/'
      fullPath: '/anveshi/'
      preLoaderRoute: typeof AnveshipublicPublicIndexRouteImport
      parentRoute: typeof AnveshipublicPublicRoute
    }
    '/anveshi/(public)/_public/$slug': {
      id: '/anveshi/(public)/_public/$slug'
      path: '/$slug'
      fullPath: '/anveshi/$slug'
      preLoaderRoute: typeof AnveshipublicPublicSlugRouteImport
      parentRoute: typeof AnveshipublicPublicRoute
    }
    '/api/qstash/crossword/schedule_listing': {
      id: '/api/qstash/crossword/schedule_listing'
      path: '/api/qstash/crossword/schedule_listing'
      fullPath: '/api/qstash/crossword/schedule_listing'
      preLoaderRoute: typeof ApiQstashCrosswordSchedule_listingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bhramitA/(public)/_public/': {
      id: '/bhramitA/(public)/_public/'
      path: '/'
      fullPath: '/bhramitA/'
      preLoaderRoute: typeof BhramitApublicPublicIndexRouteImport
      parentRoute: typeof BhramitApublicPublicRoute
    }
    '/bhramitA/(public)/_public/$slug': {
      id: '/bhramitA/(public)/_public/$slug'
      path: '/$slug'
      fullPath: '/bhramitA/$slug'
      preLoaderRoute: typeof BhramitApublicPublicSlugRouteImport
      parentRoute: typeof BhramitApublicPublicRoute
    }
    '/dvayi/(public)/_public/': {
      id: '/dvayi/(public)/_public/'
      path: '/'
      fullPath: '/dvayi/'
      preLoaderRoute: typeof DvayipublicPublicIndexRouteImport
      parentRoute: typeof DvayipublicPublicRoute
    }
    '/dvayi/(public)/_public/$slug': {
      id: '/dvayi/(public)/_public/$slug'
      path: '/$slug'
      fullPath: '/dvayi/$slug'
      preLoaderRoute: typeof DvayipublicPublicSlugRouteImport
      parentRoute: typeof DvayipublicPublicRoute
    }
    '/padajala/(public)/_public/': {
      id: '/padajala/(public)/_public/'
      path: '/'
      fullPath: '/padajala/'
      preLoaderRoute: typeof PadajalapublicPublicIndexRouteImport
      parentRoute: typeof PadajalapublicPublicRoute
    }
    '/padajala/(public)/_public/$slug': {
      id: '/padajala/(public)/_public/$slug'
      path: '/$slug'
      fullPath: '/padajala/$slug'
      preLoaderRoute: typeof PadajalapublicPublicSlugRouteImport
      parentRoute: typeof PadajalapublicPublicRoute
    }
    '/padavali/(public)/_public/': {
      id: '/padavali/(public)/_public/'
      path: '/'
      fullPath: '/padavali/'
      preLoaderRoute: typeof PadavalipublicPublicIndexRouteImport
      parentRoute: typeof PadavalipublicPublicRoute
    }
    '/padavali/(public)/_public/$slug': {
      id: '/padavali/(public)/_public/$slug'
      path: '/$slug'
      fullPath: '/padavali/$slug'
      preLoaderRoute: typeof PadavalipublicPublicSlugRouteImport
      parentRoute: typeof PadavalipublicPublicRoute
    }
    '/surUpa/(public)/_public/': {
      id: '/surUpa/(public)/_public/'
      path: '/'
      fullPath: '/surUpa/'
      preLoaderRoute: typeof SurUpapublicPublicIndexRouteImport
      parentRoute: typeof SurUpapublicPublicRoute
    }
    '/surUpa/(public)/_public/$slug': {
      id: '/surUpa/(public)/_public/$slug'
      path: '/$slug'
      fullPath: '/surUpa/$slug'
      preLoaderRoute: typeof SurUpapublicPublicSlugRouteImport
      parentRoute: typeof SurUpapublicPublicRoute
    }
    '/anveshi/(auth)/_auth/analytics/': {
      id: '/anveshi/(auth)/_auth/analytics/'
      path: '/analytics'
      fullPath: '/anveshi/analytics/'
      preLoaderRoute: typeof AnveshiauthAuthAnalyticsIndexRouteImport
      parentRoute: typeof AnveshiauthAuthRoute
    }
    '/anveshi/(auth)/_auth/edit/$id': {
      id: '/anveshi/(auth)/_auth/edit/$id'
      path: '/edit/$id'
      fullPath: '/anveshi/edit/$id'
      preLoaderRoute: typeof AnveshiauthAuthEditIdRouteImport
      parentRoute: typeof AnveshiauthAuthRoute
    }
    '/anveshi/(auth)/_auth/list/': {
      id: '/anveshi/(auth)/_auth/list/'
      path: '/list'
      fullPath: '/anveshi/list/'
      preLoaderRoute: typeof AnveshiauthAuthListIndexRouteImport
      parentRoute: typeof AnveshiauthAuthRoute
    }
    '/anveshi/(public)/_public/puzzles/': {
      id: '/anveshi/(public)/_public/puzzles/'
      path: '/puzzles'
      fullPath: '/anveshi/puzzles/'
      preLoaderRoute: typeof AnveshipublicPublicPuzzlesIndexRouteImport
      parentRoute: typeof AnveshipublicPublicRoute
    }
    '/anveshi/(public)/_public/view/$nano_id': {
      id: '/anveshi/(public)/_public/view/$nano_id'
      path: '/view/$nano_id'
      fullPath: '/anveshi/view/$nano_id'
      preLoaderRoute: typeof AnveshipublicPublicViewNano_idRouteImport
      parentRoute: typeof AnveshipublicPublicRoute
    }
    '/bhramitA/(auth)/_auth/analytics/': {
      id: '/bhramitA/(auth)/_auth/analytics/'
      path: '/analytics'
      fullPath: '/bhramitA/analytics/'
      preLoaderRoute: typeof BhramitAauthAuthAnalyticsIndexRouteImport
      parentRoute: typeof BhramitAauthAuthRoute
    }
    '/bhramitA/(auth)/_auth/edit/$id': {
      id: '/bhramitA/(auth)/_auth/edit/$id'
      path: '/edit/$id'
      fullPath: '/bhramitA/edit/$id'
      preLoaderRoute: typeof BhramitAauthAuthEditIdRouteImport
      parentRoute: typeof BhramitAauthAuthRoute
    }
    '/bhramitA/(auth)/_auth/list/': {
      id: '/bhramitA/(auth)/_auth/list/'
      path: '/list'
      fullPath: '/bhramitA/list/'
      preLoaderRoute: typeof BhramitAauthAuthListIndexRouteImport
      parentRoute: typeof BhramitAauthAuthRoute
    }
    '/bhramitA/(public)/_public/puzzles/': {
      id: '/bhramitA/(public)/_public/puzzles/'
      path: '/puzzles'
      fullPath: '/bhramitA/puzzles/'
      preLoaderRoute: typeof BhramitApublicPublicPuzzlesIndexRouteImport
      parentRoute: typeof BhramitApublicPublicRoute
    }
    '/bhramitA/(public)/_public/view/$nano_id': {
      id: '/bhramitA/(public)/_public/view/$nano_id'
      path: '/view/$nano_id'
      fullPath: '/bhramitA/view/$nano_id'
      preLoaderRoute: typeof BhramitApublicPublicViewNano_idRouteImport
      parentRoute: typeof BhramitApublicPublicRoute
    }
    '/dvayi/(auth)/_auth/analytics/': {
      id: '/dvayi/(auth)/_auth/analytics/'
      path: '/analytics'
      fullPath: '/dvayi/analytics/'
      preLoaderRoute: typeof DvayiauthAuthAnalyticsIndexRouteImport
      parentRoute: typeof DvayiauthAuthRoute
    }
    '/dvayi/(auth)/_auth/edit/$id': {
      id: '/dvayi/(auth)/_auth/edit/$id'
      path: '/edit/$id'
      fullPath: '/dvayi/edit/$id'
      preLoaderRoute: typeof DvayiauthAuthEditIdRouteImport
      parentRoute: typeof DvayiauthAuthRoute
    }
    '/dvayi/(auth)/_auth/list/': {
      id: '/dvayi/(auth)/_auth/list/'
      path: '/list'
      fullPath: '/dvayi/list/'
      preLoaderRoute: typeof DvayiauthAuthListIndexRouteImport
      parentRoute: typeof DvayiauthAuthRoute
    }
    '/dvayi/(public)/_public/puzzles/': {
      id: '/dvayi/(public)/_public/puzzles/'
      path: '/puzzles'
      fullPath: '/dvayi/puzzles/'
      preLoaderRoute: typeof DvayipublicPublicPuzzlesIndexRouteImport
      parentRoute: typeof DvayipublicPublicRoute
    }
    '/dvayi/(public)/_public/view/$nano_id': {
      id: '/dvayi/(public)/_public/view/$nano_id'
      path: '/view/$nano_id'
      fullPath: '/dvayi/view/$nano_id'
      preLoaderRoute: typeof DvayipublicPublicViewNano_idRouteImport
      parentRoute: typeof DvayipublicPublicRoute
    }
    '/padajala/(auth)/_auth/analytics/': {
      id: '/padajala/(auth)/_auth/analytics/'
      path: '/analytics'
      fullPath: '/padajala/analytics/'
      preLoaderRoute: typeof PadajalaauthAuthAnalyticsIndexRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padajala/(auth)/_auth/batch_manager/': {
      id: '/padajala/(auth)/_auth/batch_manager/'
      path: '/batch_manager'
      fullPath: '/padajala/batch_manager/'
      preLoaderRoute: typeof PadajalaauthAuthBatch_managerIndexRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padajala/(auth)/_auth/collections/$uid': {
      id: '/padajala/(auth)/_auth/collections/$uid'
      path: '/collections/$uid'
      fullPath: '/padajala/collections/$uid'
      preLoaderRoute: typeof PadajalaauthAuthCollectionsUidRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padajala/(auth)/_auth/edit/$id': {
      id: '/padajala/(auth)/_auth/edit/$id'
      path: '/edit/$id'
      fullPath: '/padajala/edit/$id'
      preLoaderRoute: typeof PadajalaauthAuthEditIdRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padajala/(auth)/_auth/list/': {
      id: '/padajala/(auth)/_auth/list/'
      path: '/list'
      fullPath: '/padajala/list/'
      preLoaderRoute: typeof PadajalaauthAuthListIndexRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padajala/(auth)/_auth/schedules/': {
      id: '/padajala/(auth)/_auth/schedules/'
      path: '/schedules'
      fullPath: '/padajala/schedules/'
      preLoaderRoute: typeof PadajalaauthAuthSchedulesIndexRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padajala/(public)/_public/archived/$id_uuid': {
      id: '/padajala/(public)/_public/archived/$id_uuid'
      path: '/archived/$id_uuid'
      fullPath: '/padajala/archived/$id_uuid'
      preLoaderRoute: typeof PadajalapublicPublicArchivedId_uuidRouteImport
      parentRoute: typeof PadajalapublicPublicRoute
    }
    '/padajala/(public)/_public/puzzle/$slug': {
      id: '/padajala/(public)/_public/puzzle/$slug'
      path: '/puzzle/$slug'
      fullPath: '/padajala/puzzle/$slug'
      preLoaderRoute: typeof PadajalapublicPublicPuzzleSlugRouteImport
      parentRoute: typeof PadajalapublicPublicRoute
    }
    '/padajala/(public)/_public/puzzles/': {
      id: '/padajala/(public)/_public/puzzles/'
      path: '/puzzles'
      fullPath: '/padajala/puzzles/'
      preLoaderRoute: typeof PadajalapublicPublicPuzzlesIndexRouteImport
      parentRoute: typeof PadajalapublicPublicRoute
    }
    '/padajala/(public)/_public/view/$nano_id': {
      id: '/padajala/(public)/_public/view/$nano_id'
      path: '/view/$nano_id'
      fullPath: '/padajala/view/$nano_id'
      preLoaderRoute: typeof PadajalapublicPublicViewNano_idRouteImport
      parentRoute: typeof PadajalapublicPublicRoute
    }
    '/padavali/(auth)/_auth/analytics/': {
      id: '/padavali/(auth)/_auth/analytics/'
      path: '/analytics'
      fullPath: '/padavali/analytics/'
      preLoaderRoute: typeof PadavaliauthAuthAnalyticsIndexRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
    '/padavali/(auth)/_auth/batch_manager/': {
      id: '/padavali/(auth)/_auth/batch_manager/'
      path: '/batch_manager'
      fullPath: '/padavali/batch_manager/'
      preLoaderRoute: typeof PadavaliauthAuthBatch_managerIndexRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
    '/padavali/(auth)/_auth/collections/$uid': {
      id: '/padavali/(auth)/_auth/collections/$uid'
      path: '/collections/$uid'
      fullPath: '/padavali/collections/$uid'
      preLoaderRoute: typeof PadavaliauthAuthCollectionsUidRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
    '/padavali/(auth)/_auth/edit/$id': {
      id: '/padavali/(auth)/_auth/edit/$id'
      path: '/edit/$id'
      fullPath: '/padavali/edit/$id'
      preLoaderRoute: typeof PadavaliauthAuthEditIdRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
    '/padavali/(auth)/_auth/list/': {
      id: '/padavali/(auth)/_auth/list/'
      path: '/list'
      fullPath: '/padavali/list/'
      preLoaderRoute: typeof PadavaliauthAuthListIndexRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
    '/padavali/(auth)/_auth/schedules/': {
      id: '/padavali/(auth)/_auth/schedules/'
      path: '/schedules'
      fullPath: '/padavali/schedules/'
      preLoaderRoute: typeof PadavaliauthAuthSchedulesIndexRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
    '/padavali/(public)/_public/archived/$id_uuid': {
      id: '/padavali/(public)/_public/archived/$id_uuid'
      path: '/archived/$id_uuid'
      fullPath: '/padavali/archived/$id_uuid'
      preLoaderRoute: typeof PadavalipublicPublicArchivedId_uuidRouteImport
      parentRoute: typeof PadavalipublicPublicRoute
    }
    '/padavali/(public)/_public/puzzle/$slug': {
      id: '/padavali/(public)/_public/puzzle/$slug'
      path: '/puzzle/$slug'
      fullPath: '/padavali/puzzle/$slug'
      preLoaderRoute: typeof PadavalipublicPublicPuzzleSlugRouteImport
      parentRoute: typeof PadavalipublicPublicRoute
    }
    '/padavali/(public)/_public/puzzles/': {
      id: '/padavali/(public)/_public/puzzles/'
      path: '/puzzles'
      fullPath: '/padavali/puzzles/'
      preLoaderRoute: typeof PadavalipublicPublicPuzzlesIndexRouteImport
      parentRoute: typeof PadavalipublicPublicRoute
    }
    '/padavali/(public)/_public/view/$nano_id': {
      id: '/padavali/(public)/_public/view/$nano_id'
      path: '/view/$nano_id'
      fullPath: '/padavali/view/$nano_id'
      preLoaderRoute: typeof PadavalipublicPublicViewNano_idRouteImport
      parentRoute: typeof PadavalipublicPublicRoute
    }
    '/surUpa/(auth)/_auth/analytics/': {
      id: '/surUpa/(auth)/_auth/analytics/'
      path: '/analytics'
      fullPath: '/surUpa/analytics/'
      preLoaderRoute: typeof SurUpaauthAuthAnalyticsIndexRouteImport
      parentRoute: typeof SurUpaauthAuthRoute
    }
    '/surUpa/(auth)/_auth/edit/$id': {
      id: '/surUpa/(auth)/_auth/edit/$id'
      path: '/edit/$id'
      fullPath: '/surUpa/edit/$id'
      preLoaderRoute: typeof SurUpaauthAuthEditIdRouteImport
      parentRoute: typeof SurUpaauthAuthRoute
    }
    '/surUpa/(auth)/_auth/list/': {
      id: '/surUpa/(auth)/_auth/list/'
      path: '/list'
      fullPath: '/surUpa/list/'
      preLoaderRoute: typeof SurUpaauthAuthListIndexRouteImport
      parentRoute: typeof SurUpaauthAuthRoute
    }
    '/surUpa/(public)/_public/puzzles/': {
      id: '/surUpa/(public)/_public/puzzles/'
      path: '/puzzles'
      fullPath: '/surUpa/puzzles/'
      preLoaderRoute: typeof SurUpapublicPublicPuzzlesIndexRouteImport
      parentRoute: typeof SurUpapublicPublicRoute
    }
    '/surUpa/(public)/_public/view/$nano_id': {
      id: '/surUpa/(public)/_public/view/$nano_id'
      path: '/view/$nano_id'
      fullPath: '/surUpa/view/$nano_id'
      preLoaderRoute: typeof SurUpapublicPublicViewNano_idRouteImport
      parentRoute: typeof SurUpapublicPublicRoute
    }
    '/padajala/(auth)/_auth/schedules/add/': {
      id: '/padajala/(auth)/_auth/schedules/add/'
      path: '/schedules/add'
      fullPath: '/padajala/schedules/add/'
      preLoaderRoute: typeof PadajalaauthAuthSchedulesAddIndexRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padajala/(auth)/_auth/schedules/edit/$id': {
      id: '/padajala/(auth)/_auth/schedules/edit/$id'
      path: '/schedules/edit/$id'
      fullPath: '/padajala/schedules/edit/$id'
      preLoaderRoute: typeof PadajalaauthAuthSchedulesEditIdRouteImport
      parentRoute: typeof PadajalaauthAuthRoute
    }
    '/padavali/(auth)/_auth/schedules/add/': {
      id: '/padavali/(auth)/_auth/schedules/add/'
      path: '/schedules/add'
      fullPath: '/padavali/schedules/add/'
      preLoaderRoute: typeof PadavaliauthAuthSchedulesAddIndexRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
    '/padavali/(auth)/_auth/schedules/edit/$id': {
      id: '/padavali/(auth)/_auth/schedules/edit/$id'
      path: '/schedules/edit/$id'
      fullPath: '/padavali/schedules/edit/$id'
      preLoaderRoute: typeof PadavaliauthAuthSchedulesEditIdRouteImport
      parentRoute: typeof PadavaliauthAuthRoute
    }
  }
}

interface AnveshiauthAuthRouteChildren {
  AnveshiauthAuthEditIdRoute: typeof AnveshiauthAuthEditIdRoute
  AnveshiauthAuthAnalyticsIndexRoute: typeof AnveshiauthAuthAnalyticsIndexRoute
  AnveshiauthAuthListIndexRoute: typeof AnveshiauthAuthListIndexRoute
}

const AnveshiauthAuthRouteChildren: AnveshiauthAuthRouteChildren = {
  AnveshiauthAuthEditIdRoute: AnveshiauthAuthEditIdRoute,
  AnveshiauthAuthAnalyticsIndexRoute: AnveshiauthAuthAnalyticsIndexRoute,
  AnveshiauthAuthListIndexRoute: AnveshiauthAuthListIndexRoute,
}

const AnveshiauthAuthRouteWithChildren = AnveshiauthAuthRoute._addFileChildren(
  AnveshiauthAuthRouteChildren,
)

interface AnveshipublicPublicRouteChildren {
  AnveshipublicPublicSlugRoute: typeof AnveshipublicPublicSlugRoute
  AnveshipublicPublicIndexRoute: typeof AnveshipublicPublicIndexRoute
  AnveshipublicPublicViewNano_idRoute: typeof AnveshipublicPublicViewNano_idRoute
  AnveshipublicPublicPuzzlesIndexRoute: typeof AnveshipublicPublicPuzzlesIndexRoute
}

const AnveshipublicPublicRouteChildren: AnveshipublicPublicRouteChildren = {
  AnveshipublicPublicSlugRoute: AnveshipublicPublicSlugRoute,
  AnveshipublicPublicIndexRoute: AnveshipublicPublicIndexRoute,
  AnveshipublicPublicViewNano_idRoute: AnveshipublicPublicViewNano_idRoute,
  AnveshipublicPublicPuzzlesIndexRoute: AnveshipublicPublicPuzzlesIndexRoute,
}

const AnveshipublicPublicRouteWithChildren =
  AnveshipublicPublicRoute._addFileChildren(AnveshipublicPublicRouteChildren)

interface AnveshiRouteRouteChildren {
  AnveshiauthAuthRoute: typeof AnveshiauthAuthRouteWithChildren
  AnveshipublicPublicRoute: typeof AnveshipublicPublicRouteWithChildren
}

const AnveshiRouteRouteChildren: AnveshiRouteRouteChildren = {
  AnveshiauthAuthRoute: AnveshiauthAuthRouteWithChildren,
  AnveshipublicPublicRoute: AnveshipublicPublicRouteWithChildren,
}

const AnveshiRouteRouteWithChildren = AnveshiRouteRoute._addFileChildren(
  AnveshiRouteRouteChildren,
)

interface BhramitAauthAuthRouteChildren {
  BhramitAauthAuthEditIdRoute: typeof BhramitAauthAuthEditIdRoute
  BhramitAauthAuthAnalyticsIndexRoute: typeof BhramitAauthAuthAnalyticsIndexRoute
  BhramitAauthAuthListIndexRoute: typeof BhramitAauthAuthListIndexRoute
}

const BhramitAauthAuthRouteChildren: BhramitAauthAuthRouteChildren = {
  BhramitAauthAuthEditIdRoute: BhramitAauthAuthEditIdRoute,
  BhramitAauthAuthAnalyticsIndexRoute: BhramitAauthAuthAnalyticsIndexRoute,
  BhramitAauthAuthListIndexRoute: BhramitAauthAuthListIndexRoute,
}

const BhramitAauthAuthRouteWithChildren =
  BhramitAauthAuthRoute._addFileChildren(BhramitAauthAuthRouteChildren)

interface BhramitApublicPublicRouteChildren {
  BhramitApublicPublicSlugRoute: typeof BhramitApublicPublicSlugRoute
  BhramitApublicPublicIndexRoute: typeof BhramitApublicPublicIndexRoute
  BhramitApublicPublicViewNano_idRoute: typeof BhramitApublicPublicViewNano_idRoute
  BhramitApublicPublicPuzzlesIndexRoute: typeof BhramitApublicPublicPuzzlesIndexRoute
}

const BhramitApublicPublicRouteChildren: BhramitApublicPublicRouteChildren = {
  BhramitApublicPublicSlugRoute: BhramitApublicPublicSlugRoute,
  BhramitApublicPublicIndexRoute: BhramitApublicPublicIndexRoute,
  BhramitApublicPublicViewNano_idRoute: BhramitApublicPublicViewNano_idRoute,
  BhramitApublicPublicPuzzlesIndexRoute: BhramitApublicPublicPuzzlesIndexRoute,
}

const BhramitApublicPublicRouteWithChildren =
  BhramitApublicPublicRoute._addFileChildren(BhramitApublicPublicRouteChildren)

interface BhramitARouteRouteChildren {
  BhramitAauthAuthRoute: typeof BhramitAauthAuthRouteWithChildren
  BhramitApublicPublicRoute: typeof BhramitApublicPublicRouteWithChildren
}

const BhramitARouteRouteChildren: BhramitARouteRouteChildren = {
  BhramitAauthAuthRoute: BhramitAauthAuthRouteWithChildren,
  BhramitApublicPublicRoute: BhramitApublicPublicRouteWithChildren,
}

const BhramitARouteRouteWithChildren = BhramitARouteRoute._addFileChildren(
  BhramitARouteRouteChildren,
)

interface DvayiauthAuthRouteChildren {
  DvayiauthAuthEditIdRoute: typeof DvayiauthAuthEditIdRoute
  DvayiauthAuthAnalyticsIndexRoute: typeof DvayiauthAuthAnalyticsIndexRoute
  DvayiauthAuthListIndexRoute: typeof DvayiauthAuthListIndexRoute
}

const DvayiauthAuthRouteChildren: DvayiauthAuthRouteChildren = {
  DvayiauthAuthEditIdRoute: DvayiauthAuthEditIdRoute,
  DvayiauthAuthAnalyticsIndexRoute: DvayiauthAuthAnalyticsIndexRoute,
  DvayiauthAuthListIndexRoute: DvayiauthAuthListIndexRoute,
}

const DvayiauthAuthRouteWithChildren = DvayiauthAuthRoute._addFileChildren(
  DvayiauthAuthRouteChildren,
)

interface DvayipublicPublicRouteChildren {
  DvayipublicPublicSlugRoute: typeof DvayipublicPublicSlugRoute
  DvayipublicPublicIndexRoute: typeof DvayipublicPublicIndexRoute
  DvayipublicPublicViewNano_idRoute: typeof DvayipublicPublicViewNano_idRoute
  DvayipublicPublicPuzzlesIndexRoute: typeof DvayipublicPublicPuzzlesIndexRoute
}

const DvayipublicPublicRouteChildren: DvayipublicPublicRouteChildren = {
  DvayipublicPublicSlugRoute: DvayipublicPublicSlugRoute,
  DvayipublicPublicIndexRoute: DvayipublicPublicIndexRoute,
  DvayipublicPublicViewNano_idRoute: DvayipublicPublicViewNano_idRoute,
  DvayipublicPublicPuzzlesIndexRoute: DvayipublicPublicPuzzlesIndexRoute,
}

const DvayipublicPublicRouteWithChildren =
  DvayipublicPublicRoute._addFileChildren(DvayipublicPublicRouteChildren)

interface DvayiRouteRouteChildren {
  DvayiauthAuthRoute: typeof DvayiauthAuthRouteWithChildren
  DvayipublicPublicRoute: typeof DvayipublicPublicRouteWithChildren
}

const DvayiRouteRouteChildren: DvayiRouteRouteChildren = {
  DvayiauthAuthRoute: DvayiauthAuthRouteWithChildren,
  DvayipublicPublicRoute: DvayipublicPublicRouteWithChildren,
}

const DvayiRouteRouteWithChildren = DvayiRouteRoute._addFileChildren(
  DvayiRouteRouteChildren,
)

interface PadajalaauthAuthRouteChildren {
  PadajalaauthAuthCollectionsUidRoute: typeof PadajalaauthAuthCollectionsUidRoute
  PadajalaauthAuthEditIdRoute: typeof PadajalaauthAuthEditIdRoute
  PadajalaauthAuthAnalyticsIndexRoute: typeof PadajalaauthAuthAnalyticsIndexRoute
  PadajalaauthAuthBatch_managerIndexRoute: typeof PadajalaauthAuthBatch_managerIndexRoute
  PadajalaauthAuthListIndexRoute: typeof PadajalaauthAuthListIndexRoute
  PadajalaauthAuthSchedulesIndexRoute: typeof PadajalaauthAuthSchedulesIndexRoute
  PadajalaauthAuthSchedulesEditIdRoute: typeof PadajalaauthAuthSchedulesEditIdRoute
  PadajalaauthAuthSchedulesAddIndexRoute: typeof PadajalaauthAuthSchedulesAddIndexRoute
}

const PadajalaauthAuthRouteChildren: PadajalaauthAuthRouteChildren = {
  PadajalaauthAuthCollectionsUidRoute: PadajalaauthAuthCollectionsUidRoute,
  PadajalaauthAuthEditIdRoute: PadajalaauthAuthEditIdRoute,
  PadajalaauthAuthAnalyticsIndexRoute: PadajalaauthAuthAnalyticsIndexRoute,
  PadajalaauthAuthBatch_managerIndexRoute:
    PadajalaauthAuthBatch_managerIndexRoute,
  PadajalaauthAuthListIndexRoute: PadajalaauthAuthListIndexRoute,
  PadajalaauthAuthSchedulesIndexRoute: PadajalaauthAuthSchedulesIndexRoute,
  PadajalaauthAuthSchedulesEditIdRoute: PadajalaauthAuthSchedulesEditIdRoute,
  PadajalaauthAuthSchedulesAddIndexRoute:
    PadajalaauthAuthSchedulesAddIndexRoute,
}

const PadajalaauthAuthRouteWithChildren =
  PadajalaauthAuthRoute._addFileChildren(PadajalaauthAuthRouteChildren)

interface PadajalapublicPublicRouteChildren {
  PadajalapublicPublicSlugRoute: typeof PadajalapublicPublicSlugRoute
  PadajalapublicPublicIndexRoute: typeof PadajalapublicPublicIndexRoute
  PadajalapublicPublicArchivedId_uuidRoute: typeof PadajalapublicPublicArchivedId_uuidRoute
  PadajalapublicPublicPuzzleSlugRoute: typeof PadajalapublicPublicPuzzleSlugRoute
  PadajalapublicPublicViewNano_idRoute: typeof PadajalapublicPublicViewNano_idRoute
  PadajalapublicPublicPuzzlesIndexRoute: typeof PadajalapublicPublicPuzzlesIndexRoute
}

const PadajalapublicPublicRouteChildren: PadajalapublicPublicRouteChildren = {
  PadajalapublicPublicSlugRoute: PadajalapublicPublicSlugRoute,
  PadajalapublicPublicIndexRoute: PadajalapublicPublicIndexRoute,
  PadajalapublicPublicArchivedId_uuidRoute:
    PadajalapublicPublicArchivedId_uuidRoute,
  PadajalapublicPublicPuzzleSlugRoute: PadajalapublicPublicPuzzleSlugRoute,
  PadajalapublicPublicViewNano_idRoute: PadajalapublicPublicViewNano_idRoute,
  PadajalapublicPublicPuzzlesIndexRoute: PadajalapublicPublicPuzzlesIndexRoute,
}

const PadajalapublicPublicRouteWithChildren =
  PadajalapublicPublicRoute._addFileChildren(PadajalapublicPublicRouteChildren)

interface PadajalaRouteRouteChildren {
  PadajalaauthAuthRoute: typeof PadajalaauthAuthRouteWithChildren
  PadajalapublicPublicRoute: typeof PadajalapublicPublicRouteWithChildren
}

const PadajalaRouteRouteChildren: PadajalaRouteRouteChildren = {
  PadajalaauthAuthRoute: PadajalaauthAuthRouteWithChildren,
  PadajalapublicPublicRoute: PadajalapublicPublicRouteWithChildren,
}

const PadajalaRouteRouteWithChildren = PadajalaRouteRoute._addFileChildren(
  PadajalaRouteRouteChildren,
)

interface PadavaliauthAuthRouteChildren {
  PadavaliauthAuthCollectionsUidRoute: typeof PadavaliauthAuthCollectionsUidRoute
  PadavaliauthAuthEditIdRoute: typeof PadavaliauthAuthEditIdRoute
  PadavaliauthAuthAnalyticsIndexRoute: typeof PadavaliauthAuthAnalyticsIndexRoute
  PadavaliauthAuthBatch_managerIndexRoute: typeof PadavaliauthAuthBatch_managerIndexRoute
  PadavaliauthAuthListIndexRoute: typeof PadavaliauthAuthListIndexRoute
  PadavaliauthAuthSchedulesIndexRoute: typeof PadavaliauthAuthSchedulesIndexRoute
  PadavaliauthAuthSchedulesEditIdRoute: typeof PadavaliauthAuthSchedulesEditIdRoute
  PadavaliauthAuthSchedulesAddIndexRoute: typeof PadavaliauthAuthSchedulesAddIndexRoute
}

const PadavaliauthAuthRouteChildren: PadavaliauthAuthRouteChildren = {
  PadavaliauthAuthCollectionsUidRoute: PadavaliauthAuthCollectionsUidRoute,
  PadavaliauthAuthEditIdRoute: PadavaliauthAuthEditIdRoute,
  PadavaliauthAuthAnalyticsIndexRoute: PadavaliauthAuthAnalyticsIndexRoute,
  PadavaliauthAuthBatch_managerIndexRoute:
    PadavaliauthAuthBatch_managerIndexRoute,
  PadavaliauthAuthListIndexRoute: PadavaliauthAuthListIndexRoute,
  PadavaliauthAuthSchedulesIndexRoute: PadavaliauthAuthSchedulesIndexRoute,
  PadavaliauthAuthSchedulesEditIdRoute: PadavaliauthAuthSchedulesEditIdRoute,
  PadavaliauthAuthSchedulesAddIndexRoute:
    PadavaliauthAuthSchedulesAddIndexRoute,
}

const PadavaliauthAuthRouteWithChildren =
  PadavaliauthAuthRoute._addFileChildren(PadavaliauthAuthRouteChildren)

interface PadavalipublicPublicRouteChildren {
  PadavalipublicPublicSlugRoute: typeof PadavalipublicPublicSlugRoute
  PadavalipublicPublicIndexRoute: typeof PadavalipublicPublicIndexRoute
  PadavalipublicPublicArchivedId_uuidRoute: typeof PadavalipublicPublicArchivedId_uuidRoute
  PadavalipublicPublicPuzzleSlugRoute: typeof PadavalipublicPublicPuzzleSlugRoute
  PadavalipublicPublicViewNano_idRoute: typeof PadavalipublicPublicViewNano_idRoute
  PadavalipublicPublicPuzzlesIndexRoute: typeof PadavalipublicPublicPuzzlesIndexRoute
}

const PadavalipublicPublicRouteChildren: PadavalipublicPublicRouteChildren = {
  PadavalipublicPublicSlugRoute: PadavalipublicPublicSlugRoute,
  PadavalipublicPublicIndexRoute: PadavalipublicPublicIndexRoute,
  PadavalipublicPublicArchivedId_uuidRoute:
    PadavalipublicPublicArchivedId_uuidRoute,
  PadavalipublicPublicPuzzleSlugRoute: PadavalipublicPublicPuzzleSlugRoute,
  PadavalipublicPublicViewNano_idRoute: PadavalipublicPublicViewNano_idRoute,
  PadavalipublicPublicPuzzlesIndexRoute: PadavalipublicPublicPuzzlesIndexRoute,
}

const PadavalipublicPublicRouteWithChildren =
  PadavalipublicPublicRoute._addFileChildren(PadavalipublicPublicRouteChildren)

interface PadavaliRouteRouteChildren {
  PadavaliauthAuthRoute: typeof PadavaliauthAuthRouteWithChildren
  PadavalipublicPublicRoute: typeof PadavalipublicPublicRouteWithChildren
}

const PadavaliRouteRouteChildren: PadavaliRouteRouteChildren = {
  PadavaliauthAuthRoute: PadavaliauthAuthRouteWithChildren,
  PadavalipublicPublicRoute: PadavalipublicPublicRouteWithChildren,
}

const PadavaliRouteRouteWithChildren = PadavaliRouteRoute._addFileChildren(
  PadavaliRouteRouteChildren,
)

interface SurUpaauthAuthRouteChildren {
  SurUpaauthAuthEditIdRoute: typeof SurUpaauthAuthEditIdRoute
  SurUpaauthAuthAnalyticsIndexRoute: typeof SurUpaauthAuthAnalyticsIndexRoute
  SurUpaauthAuthListIndexRoute: typeof SurUpaauthAuthListIndexRoute
}

const SurUpaauthAuthRouteChildren: SurUpaauthAuthRouteChildren = {
  SurUpaauthAuthEditIdRoute: SurUpaauthAuthEditIdRoute,
  SurUpaauthAuthAnalyticsIndexRoute: SurUpaauthAuthAnalyticsIndexRoute,
  SurUpaauthAuthListIndexRoute: SurUpaauthAuthListIndexRoute,
}

const SurUpaauthAuthRouteWithChildren = SurUpaauthAuthRoute._addFileChildren(
  SurUpaauthAuthRouteChildren,
)

interface SurUpapublicPublicRouteChildren {
  SurUpapublicPublicSlugRoute: typeof SurUpapublicPublicSlugRoute
  SurUpapublicPublicIndexRoute: typeof SurUpapublicPublicIndexRoute
  SurUpapublicPublicViewNano_idRoute: typeof SurUpapublicPublicViewNano_idRoute
  SurUpapublicPublicPuzzlesIndexRoute: typeof SurUpapublicPublicPuzzlesIndexRoute
}

const SurUpapublicPublicRouteChildren: SurUpapublicPublicRouteChildren = {
  SurUpapublicPublicSlugRoute: SurUpapublicPublicSlugRoute,
  SurUpapublicPublicIndexRoute: SurUpapublicPublicIndexRoute,
  SurUpapublicPublicViewNano_idRoute: SurUpapublicPublicViewNano_idRoute,
  SurUpapublicPublicPuzzlesIndexRoute: SurUpapublicPublicPuzzlesIndexRoute,
}

const SurUpapublicPublicRouteWithChildren =
  SurUpapublicPublicRoute._addFileChildren(SurUpapublicPublicRouteChildren)

interface SurUpaRouteRouteChildren {
  SurUpaauthAuthRoute: typeof SurUpaauthAuthRouteWithChildren
  SurUpapublicPublicRoute: typeof SurUpapublicPublicRouteWithChildren
}

const SurUpaRouteRouteChildren: SurUpaRouteRouteChildren = {
  SurUpaauthAuthRoute: SurUpaauthAuthRouteWithChildren,
  SurUpapublicPublicRoute: SurUpapublicPublicRouteWithChildren,
}

const SurUpaRouteRouteWithChildren = SurUpaRouteRoute._addFileChildren(
  SurUpaRouteRouteChildren,
)

interface HubRouteChildren {
  HubPuzzlesRoute: typeof HubPuzzlesRoute
  HubIndexRoute: typeof HubIndexRoute
  HubCollectionsSlugRoute: typeof HubCollectionsSlugRoute
}

const HubRouteChildren: HubRouteChildren = {
  HubPuzzlesRoute: HubPuzzlesRoute,
  HubIndexRoute: HubIndexRoute,
  HubCollectionsSlugRoute: HubCollectionsSlugRoute,
}

const HubRouteWithChildren = HubRoute._addFileChildren(HubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AnveshiRouteRoute: AnveshiRouteRouteWithChildren,
  BhramitARouteRoute: BhramitARouteRouteWithChildren,
  DvayiRouteRoute: DvayiRouteRouteWithChildren,
  PadajalaRouteRoute: PadajalaRouteRouteWithChildren,
  PadavaliRouteRoute: PadavaliRouteRouteWithChildren,
  SurUpaRouteRoute: SurUpaRouteRouteWithChildren,
  HubRoute: HubRouteWithChildren,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  Sitemap0DotxmlRoute: Sitemap0DotxmlRoute,
  Sitemap1DotxmlRoute: Sitemap1DotxmlRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  CollectionsListRoute: CollectionsListRoute,
  CrosswordSplatRoute: CrosswordSplatRoute,
  TagsListRoute: TagsListRoute,
  ApiQstashNew_puzzle_notificationRoute: ApiQstashNew_puzzle_notificationRoute,
  ApiQstashSave_ai_batch_resultsRoute: ApiQstashSave_ai_batch_resultsRoute,
  ApiQstashSchedule_listingRoute: ApiQstashSchedule_listingRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  CollectionsEditUidRoute: CollectionsEditUidRoute,
  TagsEditSlugRoute: TagsEditSlugRoute,
  ApiQstashCrosswordSchedule_listingRoute:
    ApiQstashCrosswordSchedule_listingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
