name: App Checks

on:
  - push

env:
  NEXT_PUBLIC_BETTER_AUTH_URL: http://localhost:3000
  PG_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
  QSTASH_TOKEN: 1234567890
  QSTASH_URL: http://localhost:8080
  QSTASH_CURRENT_SIGNING_KEY: 1234567890
  QSTASH_NEXT_SIGNING_KEY: 1234567890
  UPSTASH_REDIS_REST_URL: http://localhost:8080
  UPSTASH_REDIS_REST_TOKEN: 1234567890
  AWS_S3_FILES_BUCKET_NAME: example-bucket
  AWS_ACCESS_KEY_ID: EXAMPLEACCESSKEYID1234
  AWS_SECRET_ACCESS_KEY: EXAMPLESECRETACCESSKEY5678
  AWS_REGION: us-west-231
  OPENROUTER_API_KEY: sk-or-example0000000000000

jobs:
  type_build_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: |
          bun run check
          bun run build
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run test
